### ISSUE TITLE
[Bug]: Global crash when switching player styles

### ISSUE THREAD

**Issue by 526awd** [chr56/Phonograph_Plus#111]
### Bug Summary

Global crash when switching player appearance in settings

### Version

1.0.1

### Steps to reproduce the bug

Top left corner - Settings - Main Player Appearance - Toggle

### Screenshots or Screen recordings

https://github.com/chr56/Phonograph_Plus/assets/62787078/352d951a-108d-4ee0-a00e-852563ae055f

### Environment

The system is Android 13
rom is AlphaDroid

### Other helpful information

崩溃信息
Crash Report:

Package name:    player.phonograph.plus
App version:     1.0.1 (1001)
Git Commit Hash: 543ee277190bd8c0fb89
Android version: 13 (SDK 33)
Device brand:    Xiaomi  (by Xiaomi)
Device model:    Redmi 8 (code: olive)
Product name:    lineage_mi439
Build version:   TQ3A.230705.001.B4 release-keys 
                 (1689854164)
Hardware:        qcom
Language:        zh

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.g1.P(SourceFile:38)
	at androidx.fragment.app.a.l(SourceFile:66)
	at androidx.fragment.app.a.d(Unknown Source:1)
	at player.phonograph.ui.activities.base.AbsSlidingMusicPanelActivity.access$setupPlayerFragment(SourceFile:50)
	at player.phonograph.ui.activities.base.k.c(SourceFile:41)
	at player.phonograph.ui.activities.base.k.a(SourceFile:47)
	at kotlinx.coroutines.flow.d.a(Unknown Source:90)
	at lb.h.a(Unknown Source:66)
	at h7.v.invoke(SourceFile:5)
	at h7.u.d(SourceFile:135)
	at h7.u.a(Unknown Source:0)
	at r2.a0.a(Unknown Source:74)
	at kotlinx.coroutines.flow.z.a(Unknown Source:82)
	at kotlinx.coroutines.flow.m1.d(SourceFile:187)
	at kotlinx.coroutines.flow.l1.invokeSuspend(Unknown Source:12)
	at o6.a.resumeWith(Unknown Source:8)
	at e7.l0.run(Unknown Source:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7977)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
	Suppressed: e7.j0: [x1{Cancelling}@6d1fca8, Dispatchers.Main.immediate]

**Comment by 526awd** [comment]
https://github.com/chr56/Phonograph_Plus/assets/62787078/39874df2-7acb-4b69-8d6a-1fb0d24a2d62

**Comment by chr56** [comment]
?

**Comment by chr56** [comment]
Comfirmed

**Comment by chr56** [comment]
Fixed in [v1.0.2](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.0.2). Close
