### ISSUE TITLE
[Crash Report]: Application crashed after rebooting devices

### ISSUE THREAD

**Issue by alphanerdgen** [chr56/Phonograph_Plus#114]
### Crash log

```
Crash Report:

Package name:    player.phonograph.plus
App version:     1.0.1 (1001)
Git Commit Hash: 543ee277190bd8c0fb89
Android version: 12 (SDK 31)
Device brand:    samsung  (by samsung)
Device model:    
Product name:   
Build version:   
Hardware:        exynos
Language:        en

java.lang.IllegalArgumentException: Volume external_primary not found
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
at android.content.ContentResolver.query(ContentResolver.java:1226)
at android.content.ContentResolver.query(ContentResolver.java:1158)
at android.content.ContentResolver.query(ContentResolver.java:1114)
at db.b.queryAudio(Unknown Source:30)
at db.b.querySongs$default(SourceFile:63)
at fb.a.a(SourceFile:188)
at player.phonograph.service.MusicService.onLoadChildren(SourceFile:166)
at androidx.media.s.onLoadChildren(SourceFile:21)
at android.service.media.MediaBrowserService.performLoadChildren(MediaBrowserService.java:709)
at android.service.media.MediaBrowserService.addSubscription(MediaBrowserService.java:639)
at android.service.media.MediaBrowserService.access$500(MediaBrowserService.java:77)
at android.service.media.MediaBrowserService$ServiceBinder$3.run(MediaBrowserService.java:299)
at android.os.Handler.handleCallback(Handler.java:938)
at 
android.os.Handler.dispatchMessage(Handler.java:99)
at 
android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8751)
at 
java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

### Other helpful information

Downloaded from F-Droid.

### Version

1.0.1

**Comment by alphanerdgen** [comment]
@chr56 This particular crash is happening in v 1.0.2 as well. Didn't want to create a new issue just for it.

**Comment by chr56** [comment]
I am not sure what happened exactly, and I can reproduce it as well on Android 13. This is bug caused by introducing Android Auto support. This might be caused by Storage not being prepare after reboot instantly.

_I could not fix currently._

However, I try to _prevent the crash_ in [preview_1.1-beta1](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.1-beta1) (only send an error notification), but I have not tested yet.

**Comment by chr56** [comment]
[v1.1.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.1.0) released!

**Comment by chr56** [comment]
Close due to over 3 weeks.
