### ISSUE TITLE
[Crash Report]: Can not load lyrics

### ISSUE THREAD

**Issue by htetoh** [chr56/Phonograph_Plus#116]
### Crash log

```
Crash Report:

Package name:    player.phonograph.plus.preview
App version:     1.1-dev3 (1004)
Git Commit Hash: 6bcf5a8b8016358078045f4726cac1fd19dc2672
Android version: 10 (SDK 29)
Device brand:    samsung  (by samsung)
Device model:    SM-A605G (code: a6plte)
Product name:    a6pltedx
Build version:   QP1A.190711.020.A605GDXU9CVB1 
                 (A605GDXU9CVB1)
Hardware:        qcom
Language:        en

java.util.NoSuchElementException: List is empty.
	at j6.s.q(SourceFile:22)
	at xb.i2.onViewCreated(SourceFile:32)
	at androidx.fragment.app.Fragment.performViewCreated(Unknown Source:4)
	at androidx.fragment.app.o1.e(Unknown Source:226)
	at androidx.fragment.app.o1.k(SourceFile:172)
	at androidx.fragment.app.p1.t(Unknown Source:30)
	at androidx.fragment.app.g1.x0(SourceFile:28)
	at androidx.fragment.app.g1.L(Unknown Source:9)
	at androidx.fragment.app.g1.N(Unknown Source:1)
	at androidx.fragment.app.Fragment.performViewCreated(Unknown Source:9)
	at androidx.fragment.app.o1.e(Unknown Source:226)
	at androidx.fragment.app.o1.k(SourceFile:172)
	at androidx.fragment.app.p1.t(Unknown Source:30)
	at androidx.fragment.app.g1.x0(SourceFile:28)
	at androidx.fragment.app.g1.L(Unknown Source:9)
	at androidx.fragment.app.g1.q(Unknown Source:11)
	at androidx.fragment.app.p0.c(Unknown Source:4)
	at androidx.fragment.app.l0.onStart(Unknown Source:20)
	at androidx.appcompat.app.n.onStart(Unknown Source:0)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
	at android.app.Activity.performStart(Activity.java:7978)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3512)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2175)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7860)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

```

### Screenshots or Screen recordings

https://github.com/chr56/Phonograph_Plus/assets/70825624/425c696f-e83a-4a8f-8eac-f861d7fe8f2b

### Version

1.1-dev3

**Comment by chr56** [comment]
How to reproduce this? Or when this happened?

**Comment by htetoh** [comment]
> How to reproduce this? Or when this happened?

Happened while playing a track.

**Comment by chr56** [comment]
Temporarily turn off Lyrics Function in Setting.

**Comment by htetoh** [comment]
> Temporarily turn off Lyrics Function in Setting.

I added screen recording.

**Comment by chr56** [comment]
This happened when you manually loaded a file that **isn't a lyrics file (txt/lrc)** at all. What file have you loaded?

**Comment by htetoh** [comment]
> This happened when you manually loaded a file that **isn't a lyrics file (txt/lrc)** at all. What file have you loaded?

Happened on .conf .jpg .mp4 and also .txt

**Comment by htetoh** [comment]
> This happened when you manually loaded a file that **isn't a lyrics file (txt/lrc)** at all. What file have you loaded?

Also with .lrc

```
Crash Report:

Package name:    player.phonograph.plus.preview
App version:     1.1-dev3 (1004)
Git Commit Hash: 6bcf5a8b8016358078045f4726cac1fd19dc2672
Android version: 10 (SDK 29)
Device brand:    samsung  (by samsung)
Device model:    SM-A605G (code: a6plte)
Product name:    a6pltedx
Build version:   QP1A.190711.020.A605GDXU9CVB1 
                 (A605GDXU9CVB1)
Hardware:        qcom
Language:        en

java.lang.IllegalStateException: Fragment i2{940de8b} (27b71467-380d-4eef-962c-6851eb199d41) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(SourceFile:18)
	at xb.m.invoke(SourceFile:31)
	at lib.phonograph.misc.a.onActivityResult(Unknown Source:8)
	at androidx.activity.result.ActivityResultRegistry$1.c(Unknown Source:69)
	at androidx.lifecycle.y.a(SourceFile:23)
	at androidx.lifecycle.z.k(SourceFile:332)
	at androidx.lifecycle.z.i(Unknown Source:34)
	at androidx.lifecycle.z.g(Unknown Source:14)
	at androidx.lifecycle.l.e(Unknown Source:26)
	at androidx.lifecycle.s0.onActivityPostStarted(Unknown Source:9)
	at android.app.Activity.dispatchActivityPostStarted(Activity.java:1278)
	at android.app.Activity.performStart(Activity.java:8018)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3512)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2175)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7860)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

```

**Comment by chr56** [comment]
[v1.1.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.1.0) released! Close!
