### ISSUE TITLE
[Crash Report]: Crash after opening

### ISSUE THREAD

**Issue by alphanerdgen** [chr56/Phonograph_Plus#117]
### Crash log

```
Crash Report:

Package name:    player.phonograph.plus
App version:     1.0.2 (1002)
Git Commit Hash: 1298bd36464d1786c96a
Android version: 12 (SDK 31)
Device brand:    samsung  (by samsung)
Device model:    
Product name:
Build version:
Hardware: exynos
Language:  en

java.lang.IllegalStateException: Fragment CardPlayerFragment{88bccbc} (4a6e7b48-1ad9-424d-a8f4-c5b4fde893e5) did not return a View from onCreateView() or this was called before onCreateView().
at androidx.fragment.app.Fragment.requireView(SourceFile:18)
at player.phonograph.ui.fragments.player.card.d.d(Unknown Source:4)
at player.phonograph.ui.fragments.player.card.f.onGlobalLayout(Unknown Source:15)
at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1080)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4098)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2924)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10513)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
at android.view.Choreographer.doCallbacks(Choreographer.java:866)
at android.view.Choreographer.doFrame(Choreographer.java:797)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8751)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

### Steps to reproduce the bug

Download the apk from GitHub and install it. This happens soon after opening the app.

### Version

1.0.2

**Comment by chr56** [comment]
try [preview_1.1-beta1](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.1-beta1). It should be fixed since this version.

**Comment by chr56** [comment]
[v1.1.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.1.0) released! It should be fixed, Close!
