### ISSUE TITLE
App gets crashing while using theme switching 

### ISSUE THREAD

**Issue by Bhanup85** [chr56/Phonograph_Plus#120]
### Crash log

Crash Report:

Package name:    player.phonograph.plus
App version:     1.0.2 (1002)
Git Commit Hash: 1298bd36464d1786c96a
Android version: 12 (SDK 31)
Device brand:    realme  (by realme)
Device model:    RMX2151 (code: RMX2151L1)
Product name:    RMX2151
Build version:   RMX2151_11_F.11 
                 (Q.bf75e7-1)
Hardware:        mt6785
Language:        en

java.lang.IllegalStateException: Fragment CardPlayerFragment{b63bc50} (24496d21-d1fb-4f47-b808-77f27380f4da) did not return a View from onCreateView() or this was called before onCreateView().
	at androidx.fragment.app.Fragment.requireView(SourceFile:18)
	at player.phonograph.ui.fragments.player.card.d.d(Unknown Source:4)
	at player.phonograph.ui.fragments.player.card.f.onGlobalLayout(Unknown Source:15)
	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1061)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3576)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2416)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9478)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1242)
	at android.view.Choreographer.doCallbacks(Choreographer.java:996)
	at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:383)
	at android.view.Choreographer.doFrame(Choreographer.java:865)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1227)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

### Version

1.0.2

### Steps to reproduce the bug

While switching the theme

**Comment by chr56** [comment]
Sorry, I can not reproduce this in version v1.1.0.

And this should be fixed along with `Crash when resizing window`.

Please upgrade to v1.1.0.

(PS: F-droid Reproducible Build is enabled, no signature issue if installing GitHib Release version. No uninstall before reinstall.)
