### ISSUE TITLE
[Crash Report]: Regular crash reports popup on front of the phone while application isn't even playing

### ISSUE THREAD

**Issue by Porkepix** [chr56/Phonograph_Plus#124]
### Crash log

```
Crash Report:

Package name:    player.phonograph.plus
App version:     1.1.0 (1010)
Git Commit Hash: 374a7e2791709a079348795f90898da90cba8a7e
Android version: 8.0.0 (SDK 26)
Device brand:    Sony  (by Sony)
Device model:    F8331 (code: F8331)
Product name:    F8331
Build version:   41.3.A.2.192 
                 (1629831864)
Hardware:        qcom
Language:        en

j6.z: lateinit property mediaSession has not been initialized
	at kb.e.a(Unknown Source:7)
	at kb.e.c(SourceFile:15)
	at player.phonograph.service.MusicService.d(SourceFile:341)
	at player.phonograph.service.MusicService.access$notifyChange(SourceFile:1)
	at player.phonograph.service.d.onCurrentPositionChanged(Unknown Source:4)
	at lb.d.b(Unknown Source:18)
	at lb.i.run(SourceFile:14)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:251)
	at android.os.HandlerThread.run(HandlerThread.java:65)

```

### Version

1.1.0

### Steps to reproduce the bug

No STR, it appens here and there while the application isn't even in use. It can even happens when the application was not used a single time since last reboot.

### Other helpful information

Issue isn't new and already existed on previous versions.

**Comment by chr56** [comment]
I am not quite sure its cause. Try to force kill app to avoid, for now.

**Comment by chr56** [comment]
Yes, and actually, I am wonder if it is caused by AndroidAuto. Last month, I receive the report of crash after rebooting (#114). And that is due to trying to "be launched" by AndroidAuto when device internal storage is not ready.

But yours is caused by Queue position changed when mediasession is not ready.

**Comment by chr56** [comment]
Same crash report？

Note: 
You can obtains all past error logs at `/storage/emulated/0/Android/data/player.phonograph.plus/cache/errors.txt` unless you cleaned recently.

**Comment by chr56** [comment]
It is 2025, this crash (in v1.1.0) is no longer suitable for current versions (v1.8.x & v1.9.0).
But this issue is also similar to issues #211 #234 #255 as well.

Close for outdated!
