### ISSUE TITLE
[Crash Report]: crash reports popup at phone startup

### ISSUE THREAD

**Issue by ayoahha** [chr56/Phonograph_Plus#129]
### Crash log

```
Internal Error:

Package name:    player.phonograph.plus
App version:     1.3.1 (1031)
Git Commit Hash: 2721533f9cdc69d5af23acb709e8c8e0f22e689d
Android version: 14 (SDK 34)
Device brand:    google  (by Google)
Device model:    Pixel 6 (code: oriole)
Product name:    oriole
Build version:   UP1A.231005.007.2023101300 
                 (2023101300)
Hardware:        oriole
Language:        fr

Failed to query audio via MediaStore
java.lang.IllegalArgumentException: Volume external_primary not found
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:495)
	at android.content.ContentResolver.query(ContentResolver.java:1235)
	at android.content.ContentResolver.query(ContentResolver.java:1167)
	at android.content.ContentResolver.query(ContentResolver.java:1123)
	at fc.l.queryAudio(SourceFile:1)
	at fc.l.querySongs$default(SourceFile:50)
	at ec.a.f(SourceFile:22)
	at a2.q0.l1(SourceFile:67)
	at kc.d.x(SourceFile:1)
	at kc.t.a(SourceFile:10)
	at kc.i.run(SourceFile:13)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
}
```

### Version

1.3.2

### Steps to reproduce the bug

Those messages (there are usualky 4-5 messages) appear when i start the phone... I'm on grapheneOS latest but it was the same behaviour on older releases.

### Other helpful information

GrapheneOS

**Comment by chr56** [comment]
See also #114.

**Comment by ayoahha** [comment]
> See also #114.

Not sure there is a link, but un any case, issue 114 is closed !

**Comment by chr56** [comment]
[v1.4.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.4.0) is released!
Close
