### ISSUE TITLE
[Crash Report]: Crashed immediately after opening audio files from file manager

### ISSUE THREAD

**Issue by iripu** [chr56/Phonograph_Plus#130]
### Crash log

```
Package name:    [player.phonograph.plus](http://player.phonograph.plus/)
App version:     1.3.1 (1031)
Git Commit Hash: 2721533f9cdc69d5af23acb709e8c8e0f22e689d
Android version: 12 (SDK 31)
Device brand:    POCO  (by Xiaomi)
Device model:    220733SPH (code: snow)
Product name:    snow_p_in
Build version:   12 V13.0.12.0.SGMINXM 
                 (V13.0.12.0.SGMINXM)
Hardware:        mt6761
Language:        en

java.lang.RuntimeException: Unable to start activity ComponentInfo{[player.phonograph.plus/player.phonograph.ui.activities.StarterActivity](http://player.phonograph.plus/player.phonograph.ui.activities.StarterActivity)}: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3675)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3832)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2247)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7886)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$[MethodAndArgsCaller.run](http://methodandargscaller.run/)(RuntimeInit.java:568)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at player.phonograph.ui.activities.v1.e(SourceFile:137)
	at player.phonograph.ui.activities.StarterActivity.onCreate(SourceFile:826)
	at android.app.Activity.performCreate(Activity.java:8050)
	at android.app.Activity.performCreate(Activity.java:8030)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3648)
	... 12 more
```

### Version

1.3.1

### Steps to reproduce the bug

Tap mp3 file on default file manager, select Phonograph as player on popup

**Comment by chr56** [comment]
Check permission.
Make sure granting full storage permission to Phonograph Plus. 
(Tips: `Main Drawer` -> `More` -> `Grant External Storage Permission`)

**Comment by chr56** [comment]
Are you choosing songs from (external and physical) SD card?

**Comment by chr56** [comment]
Excuse me, can you tell me which file manager you are using?

**Comment by chr56** [comment]
Try this revision:
[PhonographPlusPreview_24ff05d5f.zip](https://github.com/chr56/Phonograph_Plus/files/14018360/PhonographPlusPreview_24ff05d5f.zip)

**Comment by chr56** [comment]
Preview version [v1.4.4-dev1](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.4.4-dev1) has been released!

The problem should be fixed (but there are also some user reports of failing on some file managers).

**Comment by chr56** [comment]
Stable Release [v1.4.4](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.4.4) has been released!

I think the problem has been fixed. 

Close!
