### ISSUE TITLE
[Bug Report] Crash on Sleep Timer

### ISSUE THREAD

**Issue by maemunman** [chr56/Phonograph_Plus#14]
**Describe the bug or unexpected behavior**
App crashes if you click "Sleep Timer", thus a timer cannot be set.

**Crash log**
If app crashed, copy the logs if available.
```
Crash Report:

Package name:    player.phonograph.plus
App version:     0.2.6.1.LTS (226)
Git Commit Hash: a22661ac452a0b6ee06d
Android version: 12 (SDK 31)
Device brand:    samsung  (by samsung)
Device model:    SM-G981U (code: x1q)
Product name:    x1qsqx
Build version:   SP1A.210812.016.G981USQU2FVF1 
                 (G981USQU2FVF1)
Hardware:        qcom
Language:        fa

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at android.app.SharedPreferencesImpl.getLong(SharedPreferencesImpl.java:329)
	at z7.a$d.a(Unknown Source:15)
	at z7.a.getNextSleepTimerElapsedRealTime(Unknown Source:8)
	at j7.a0$c.<init>(Unknown Source:8)
	at j7.a0.onCreateDialog(Unknown Source:300)
	at androidx.fragment.app.m.prepareDialog(Unknown Source:13)
	at androidx.fragment.app.m.onGetLayoutInflater(Unknown Source:16)
	at androidx.fragment.app.Fragment.performGetLayoutInflater(Unknown Source:0)
	at androidx.fragment.app.g0.f(SourceFile:2)
	at androidx.fragment.app.g0.l(SourceFile:3)
	at androidx.fragment.app.z.Q(SourceFile:15)
	at androidx.fragment.app.z.D0(Unknown Source:91)
	at androidx.fragment.app.z.O(SourceFile:2)
	at androidx.fragment.app.z$d.run(Unknown Source:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)


```

**How to reproduce**
Steps to reproduce the bugs or unexpected behaviors:
* Have songs playing. 
* Go to three dot menu
* Click sleep timer
* crash

**Screenshots (Optional)**
(if available)

**Other information**
This is a new issue, beginning in the most recent version on fdroid, 0.2.6.1LTS

**Comment by chr56** [comment]
If possible, try to clean/reset app setting (Setting->"three dot menu"). And try to go to sleep time again!

If it still crashed, unzip [Phonograph Plus CI Build](https://github.com/chr56/Phonograph_Plus/suites/7333759197/artifacts/296987468) and install application `Phonograph Plus CI Build` to test again.

**Comment by maemunman** [comment]
Clearing settings does fix it. Importing settings from old file breaks it again. The settings file was saved at a time when it was working fine, but it's not much of a hassle to recreate those settings.
