### ISSUE TITLE
[Crash Report] Crash when opening files from file manager

### ISSUE THREAD

**Issue by tux18031** [chr56/Phonograph_Plus#140]
### Crash log

```
Crash Report:

Package name:    player.phonograph.plus
App version:     1.4.2 (1042)
Git Commit Hash: 45ddb146603d51306c32c31a80ca2bc1ad620e86
Android version: 14 (SDK 34)
Device brand:    google  (by Google)
Device model:    Pixel 7 Pro (code: cheetah)
Product name:    cheetah
Build version:   UQ1A.231205.015 
                 (11084887)
Hardware:        cheetah
Language:        de


Stack Track:
java.lang.RuntimeException: Unable to start activity ComponentInfo{player.phonograph.plus/player.phonograph.ui.activities.StarterActivity}: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3802)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3942)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2448)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8194)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at player.phonograph.ui.activities.v1.e(SourceFile:142)
	at player.phonograph.ui.activities.StarterActivity.onCreate(SourceFile:831)
	at android.app.Activity.performCreate(Activity.java:8621)
	at android.app.Activity.performCreate(Activity.java:8599)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3784)
	... 12 more
```

### Version

1.4.2

### Steps to reproduce the bug

It doesn't matter whether the app is set up and has all authorizations or has been reset.  when an mp3 file is opened externally via a file manager.  the app crashes

**Comment by chr56** [comment]
Physical external SD card?

**Comment by tux18031** [comment]
> Are you using _physical external_ SD card?
 physical

**Comment by tux18031** [comment]
> Are you using _physical external_ SD card?

physical

**Comment by tux18031** [comment]
no. is from internal memory

**Comment by chr56** [comment]
> > Are you using _physical external_ SD card?
> 
> physical

If so, this is a known issue, which is maybe duplicated with issue #130.

**Comment by chr56** [comment]
Well, can you tell me which file manager you are using?

**Comment by chr56** [comment]
Try this revision:
[PhonographPlusPreview_24ff05d5f.zip](https://github.com/chr56/Phonograph_Plus/files/14018360/PhonographPlusPreview_24ff05d5f.zip)

**Comment by tux18031** [comment]
> Preview version [v1.4.4-dev1](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.4.4-dev1) has been released!
> 
> The problem should be fixed (but there are also user reports of failing on some file managers).

The bug has been fixed with this version.
I use this file manager https://play.google.com/store/apps/details?id=pl.solidexplorer2 and he ist work with the Version 1.4.4-dev1 of Phonograph
