### ISSUE TITLE
[Crash Report] Attempting to reorder songs in queue by long press causes crash

### ISSUE THREAD

**Issue by soko7awen** [chr56/Phonograph_Plus#145]
### Crash log

```
Crash Report:

Package name:    player.phonograph.plus
App version:     1.4.2 (1042)
Git Commit Hash: 45ddb146603d51306c32c31a80ca2bc1ad620e86
Android version: 13 (SDK 33)
Device brand:    google  (by Google)
Device model:    Pixel 4a (code: sunfish)
Product name:    sunfish
Build version:   lineage_sunfish-userdebug 13 TQ3A.230705.001 eng.root.20230814.135302 dev-keys 
                 (eng.root.20230814.135302)
Hardware:        sunfish
Language:        en


Stack Track:
java.lang.IllegalStateException: dragging target must provides valid ID
	at g6.g.B(SourceFile:1)
	at g6.t.r(SourceFile:418)
	at g6.m.a(SourceFile:1)
	at androidx.recyclerview.widget.RecyclerView.K(SourceFile:1)
	at androidx.recyclerview.widget.RecyclerView.onInterceptTouchEvent(SourceFile:10)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2653)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at com.sothree.slidinguppanel.SlidingUpPanelLayout.dispatchTouchEvent(SourceFile:393)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at com.sothree.slidinguppanel.SlidingUpPanelLayout.dispatchTouchEvent(SourceFile:393)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1912)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4299)
	at androidx.appcompat.view.r.dispatchTouchEvent(Unknown Source:2)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)
	at android.view.View.dispatchPointerEvent(View.java:15309)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6778)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6578)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6222)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6279)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9206)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9157)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9126)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9329)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:247)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9286)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9420)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:824)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Version

1.4.3

### Steps to reproduce the bug

Long press on the number representing the track's place in the queue (with the intention to drag it somewhere else).

### Environment

LineageOS, but also happens on my friend's CalyxOS phone.

**Comment by chr56** [comment]
Excuse me, how many songs in your playing queue?

**Comment by soko7awen** [comment]
In mine, there are 3,544 songs. In my friend's he has 543 songs in his queue. When I create a small queue of 3 songs, the crash does not occur. Although, further testing showed the crash occurring with a reasonably sized queue of 21 songs. Thanks!

**Comment by chr56** [comment]
Try this one:
[PhonographPlusPreview-efd5db7f.zip](https://github.com/chr56/Phonograph_Plus/files/14009224/PhonographPlusPreview-efd5db7f.zip)

I **think** this revision would solve your problem.

This bug happened before, on a device with too many songs. It "was fixed", we think though.

If not, I'd like to ask several questions for more information:

1. How many songs in total in your device?
   Too many songs also means large song id in Android `MediaStore` (Phonograph Plus uses `MediaStore` ).
2. How many songs in your playing queue? (You have answered.)
   Long queue is main cause of this crash, from previous experience.
3. How long have you use this device since _last Setup Wizard_, and how do you accumulate your songs since that?
   These two questions may be quite strange and "inappropriate". 
For your circumstance (LineageOS on Pixel 4a), could you please tell me how long (not precisely, answering "years" is fine) since you install/flash LineageOS on your devices? 
And it seems that these are over one thousand songs on your devices, so please tell me how you accumulate songs or how these files "appear" on your device? For example, these songs may be "imported" from other places (Desktop, Online Drive etc.) _at once_ after LineageOS installed. (This results continuous song id, if you ask me why it matters). Or these songs are accumulated one by one, with almost random added dates. (This results, song ids have gaps among them, if you ask me why it matters). Or both, most of them are "imported" from the previous, rest of them are added one by one and day by day. 
I ask these two questions for knowing id distributions in `MediaStore` on your devices.

**Comment by chr56** [comment]
Preview version [v1.4.4-dev1](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.4.4-dev1) has been released!

Please try out, thanks.

**Comment by chr56** [comment]
Stable Release [v1.4.4](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.4.4) has been released!

Is your problems solved?

**Comment by soko7awen** [comment]
Yes! It appears that resolved the issue, thanks :D
