### ISSUE TITLE
App crashed after installing first time.

### ISSUE THREAD

**Issue by arkydon** [chr56/Phonograph_Plus#155]
### Crash log

```
Crash Report:

Package name:    player.phonograph.plus
App version:     1.5.0 (1050)
Git Commit Hash: a3ae0db9dc053c2f0b48bdc57bb7b09b9a391574
Android version: 14 (SDK 34)
Device brand:    Redmi  (by Xiaomi)
Device model:    Redmi 9 (code: lancelot)
Product name:    lineage_lancelot
Build version:   UQ1A.231205.015 release-keys 
                 (1703929376)
Hardware:        mt6768
Language:        en


Stack Track:
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at java.util.concurrent.CopyOnWriteArrayList.elementAt(CopyOnWriteArrayList.java:389)
	at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:402)
	at player.phonograph.ui.fragments.player.PlayerAlbumCoverFragment.access$refreshAdapter(SourceFile:76)
	at kf.q0.emit(SourceFile:277)
	at n9.d1.a(SourceFile:175)
	at kf.r0.invokeSuspend(SourceFile:37)
	at kf.r0.invoke(SourceFile:13)
	at androidx.lifecycle.n0.invokeSuspend(Unknown Source:32)
	at androidx.lifecycle.n0.invoke(SourceFile:13)
	at n9.p0.C(SourceFile:5)
	at i8.o.D0(SourceFile:1)
	at androidx.lifecycle.o0.invokeSuspend(Unknown Source:71)
	at t8.a.resumeWith(SourceFile:1)
	at k9.g0.run(SourceFile:1)
	at k9.r0.Z(SourceFile:24)
	at p9.a.c(SourceFile:153)
	at o9.c.W(SourceFile:12)
	at k9.a.i0(SourceFile:80)
	at i8.o.u1(SourceFile:30)
	at androidx.lifecycle.p0.f(SourceFile:21)
	at androidx.lifecycle.z.a(SourceFile:23)
	at androidx.lifecycle.a0.i(SourceFile:324)
	at androidx.lifecycle.a0.g(SourceFile:1)
	at androidx.lifecycle.a0.f(SourceFile:1)
	at ua.k.p(SourceFile:1)
	at androidx.lifecycle.t0.onActivityPostStarted(Unknown Source:9)
	at android.app.Activity.dispatchActivityPostStarted(Activity.java:1485)
	at android.app.Activity.performStart(Activity.java:8711)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3827)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2448)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8190)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
	Suppressed: p9.f: [q1{Cancelling}@bfc041a, Dispatchers.Main.immediate]


```

### Version

1.5.0

### Steps to reproduce the bug

Install app
Grant all permissions
Open app

### Environment

Android 14
CrDroid Rom
Rooted

**Comment by chr56** [comment]
Fixed in [v1.5.1](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.5.1). Close!
