### ISSUE TITLE
[Crash Report] NullPointerException after switching system theme

### ISSUE THREAD

**Issue by mb720** [chr56/Phonograph_Plus#156]
### Crash log

```
Crash Report:

Package name:    player.phonograph.plus
App version:     1.4.4 (1044)
Git Commit Hash: fed2dee21d07a2a65d48959249b44abecf671768
Android version: 14 (SDK 34)
Device brand:    google  (by Google)
Device model:    Pixel 6 Pro (code: raven)
Product name:    raven
Build version:   UQ1A.240205.002.2024020500 
                 (2024020500)
Hardware:        raven
Language:        en


Stack Track:
java.lang.NullPointerException
	at player.phonograph.ui.fragments.player.card.CardPlayerFragment.p(SourceFile:3)
	at player.phonograph.ui.fragments.player.card.CardPlayerFragment.onPanelStateChanged(SourceFile:42)
	at com.sothree.slidinguppanel.SlidingUpPanelLayout.setPanelStateInternal(SourceFile:29)
	at com.sothree.slidinguppanel.SlidingUpPanelLayout.a(SourceFile:1)
	at d8.e.l(SourceFile:81)
	at g.p0.run(SourceFile:50)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```

### Version

1.4.4

### Steps to reproduce the bug

1. Open Phonograph.
2. Change the system theme using the pull down menu. From light to dark, for example.
3. Go back to Phonograph.
4. Phonograph crashes.

### Environment

GrapheneOS on Pixel 6 Pro. Android version 15.

### Screenshots or Screen recordings

![Screenshot_20240223-234344](https://github.com/chr56/Phonograph_Plus/assets/4164548/4219f390-d464-4d85-a4c2-9ae773624a3a)

I switched themes using the "Dark theme" button from GrapheneOS' pulldown menu.

### Other helpful information

Thanks a lot for Phonograph!

**Comment by chr56** [comment]
Excuse me, I can not reproduce the bug you described.

**Comment by mb720** [comment]
After updating to Phonograph 1.5.0 today the bug is gone.
