### ISSUE TITLE
[Clash Report] Clash on MIUI14 (based on Android 13)

### ISSUE THREAD

**Issue by Radium-bit** [chr56/Phonograph_Plus#157]
Crash Report:

Package name:    player.phonograph.plus
App version:     1.5.0 (1050)
Git Commit Hash: a3ae0db9dc053c2f0b48bdc57bb7b09b9a391574
Android version: 13 (SDK 33)
Device brand:    Redmi  (by Xiaomi)
Device model:    22041216C (code: xaga)
Product name:    xaga
Build version:   TP1A.220624.014 
                 (V14.0.6.0.TLOCNXM)
Hardware:        mt6895
Language:        zh

Stack Track:
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at java.util.concurrent.CopyOnWriteArrayList.elementAt(CopyOnWriteArrayList.java:389)
	at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:402)
	at player.phonograph.ui.fragments.player.PlayerAlbumCoverFragment.access$refreshAdapter(SourceFile:76)
	at kf.q0.emit(SourceFile:277)
	at n9.d1.a(SourceFile:175)
	at kf.r0.invokeSuspend(SourceFile:37)
	at kf.r0.invoke(SourceFile:13)
	at androidx.lifecycle.n0.invokeSuspend(Unknown Source:32)
	at androidx.lifecycle.n0.invoke(SourceFile:13)
	at n9.p0.C(SourceFile:5)
	at i8.o.D0(SourceFile:1)
	at androidx.lifecycle.o0.invokeSuspend(Unknown Source:71)
	at t8.a.resumeWith(SourceFile:1)
	at k9.g0.run(SourceFile:1)
	at k9.r0.Z(SourceFile:24)
	at p9.a.c(SourceFile:153)
	at o9.c.W(SourceFile:12)
	at k9.a.i0(SourceFile:80)
	at i8.o.u1(SourceFile:30)
	at androidx.lifecycle.p0.f(SourceFile:21)
	at androidx.lifecycle.z.a(SourceFile:23)
	at androidx.lifecycle.a0.i(SourceFile:324)
	at androidx.lifecycle.a0.g(SourceFile:1)
	at androidx.lifecycle.a0.f(SourceFile:1)
	at ua.k.p(SourceFile:1)
	at androidx.lifecycle.t0.onActivityPostStarted(Unknown Source:9)
	at android.app.Activity.dispatchActivityPostStarted(Activity.java:1494)
	at android.app.Activity.performStart(Activity.java:8595)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3827)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8136)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
	Suppressed: p9.f: [q1{Cancelling}@3483bbe, Dispatchers.Main.immediate]

**Comment by chr56** [comment]
Upgrade to 1.5.1

**Comment by chr56** [comment]
This is duplicated with #155.
