### ISSUE TITLE
[Bug Report]Crash when swiping covers in player / 最新预览版播放中报错

### ISSUE THREAD

**Issue by Tartuffe-X** [chr56/Phonograph_Plus#16]
**Describe the bug or unexpected behavior**
最新预览版播放中报错

**Crash log**
Crash Report:

Package name:    player.phonograph.plus.preview
App version:     0.3-alpha08 (259)
Git Commit Hash: c2673c5213408a2c7058
Android version: 12 (SDK 31)
Device brand:    realme  (by realme)
Device model:    RMX3361 (code: RE507C)
Product name:    RMX3361
Build version:   RMX3361_11_C.08 
                 (R.202206222209)
Hardware:        qcom
Language:        zh

j1.d: Unexpected exception thrown by non-Glide code
	at j1.n.c(Unknown Source:15)
	at j1.n$b.run(Unknown Source:35)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8184)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void v6.b$a.loadAlbumCover()' on a null object reference
	at v6.b.requestLoadCover(Unknown Source:8)
	at player.phonograph.ui.fragments.player.PlayerAlbumCoverFragment.access$deployColor(SourceFile:3)
	at player.phonograph.ui.fragments.player.a.invoke(SourceFile:1)
	at v6.b$a.access$setColor(Unknown Source:12)
	at v6.b$a$b.invoke(SourceFile:1)
	at v6.a.onColorReady(Unknown Source:14)
	at f7.c.onResourceReady(SourceFile:1)
	at z1.h.s(SourceFile:2)
	at z1.h.r(SourceFile:4)
	at j1.n.c(Unknown Source:8)
	... 9 more

```

**How to reproduce**
Steps to reproduce the bugs or unexpected behaviors:
快速添加少量歌曲加入播放列表
横滑封面切换歌曲
报错

**Comment by chr56** [comment]
😅这太快了吧

已成功复现，等我修复...

**Comment by Tartuffe-X** [comment]
> 😅这太快了吧
> 
> 已成功复现，等我修复...

![Screenshot_2022-07-25-14-47-33-72_dbf920555b61727148fce70dfdbe3989](https://user-images.githubusercontent.com/53497455/180715278-4b5233bf-32a0-4ab7-936e-d8989386b71c.jpg)

这也新特性吗，播放器控件位置错误

**Comment by chr56** [comment]
> > 😅这太快了吧
> > 已成功复现，等我修复...
> 
> 这也新特性吗，播放器控件位置错误，常态化，每次进入都是这样

我的问题,，忘记测试 `Card` 了。
先换成 `Flat` 外观的`正在播放界面`，等下修复...

**Comment by Tartuffe-X** [comment]
> > > 😅这太快了吧
> > > 已成功复现，等我修复...
> > 
> > 
> > 这也新特性吗，播放器控件位置错误，常态化，每次进入都是这样
> 
> 我的问题,，忘记测试 `Card` 了。 先换成 `Flat` 外观的`正在播放界面`，等下修复...

辛苦啦

**Comment by chr56** [comment]
已于alpha08中修复
