### ISSUE TITLE
[Crash Report] 

### ISSUE THREAD

**Issue by VictorDeus** [chr56/Phonograph_Plus#173]
### Crash log

```
Crash Report:

Package name:    player.phonograph.plus
App version:     1.6.1 (1061)
Git Commit Hash: f5697850d98bb66a2005ed30b243103dca446e2a
Android version: 14 (SDK 34)
Device brand:    samsung  (by samsung)
Device model:    SM-A725F (code: a72q)
Product name:    a72qnsser
Build version:   UP1A.231005.007.A725FXXU6EWL4 
                 (A725FXXU6EWL4)
Hardware:        qcom
Language:        ru


Stacktrace:
java.lang.ArrayIndexOutOfBoundsException: length=1; index=11
 at java.util.concurrent.CopyOnWriteArrayList.elementAt(CopyOnWriteArrayList.java:389)
 at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:402)
 at player.phonograph.ui.fragments.player.PlayerAlbumCoverFragment.access$refreshAdapter(SourceFile:84)
 at mf.q0.emit(SourceFile:290)
 at m9.d1.b(SourceFile:175)
 at mf.r0.invokeSuspend(SourceFile:42)
 at mf.r0.invoke(SourceFile:13)
 at androidx.lifecycle.n0.invokeSuspend(Unknown Source:32)
 at androidx.lifecycle.n0.invoke(SourceFile:13)
 at n9.c.U(SourceFile:5)
 at i8.h.j0(SourceFile:10)
 at androidx.lifecycle.o0.invokeSuspend(Unknown Source:71)
 at s8.a.resumeWith(SourceFile:9)
 at j9.h0.run(SourceFile:92)
 at j9.s0.Z(SourceFile:24)
 at o9.a.c(SourceFile:153)
 at n9.c.T(SourceFile:12)
 at j9.a.i0(SourceFile:91)
 at i8.h.o1(SourceFile:36)
 at androidx.lifecycle.p0.e(SourceFile:20)
 at androidx.lifecycle.z.a(SourceFile:23)
 at androidx.lifecycle.a0.i(SourceFile:324)
 at androidx.lifecycle.a0.g(SourceFile:1)
 at androidx.lifecycle.a0.f(SourceFile:1)
 at va.a.u(SourceFile:27)
 at androidx.lifecycle.t0.onActivityPostStarted(Unknown Source:9)
 at android.app.Activity.dispatchActivityPostStarted(Activity.java:1499)
 at android.app.Activity.performStart(Activity.java:9016)
 at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4198)
 at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
 at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
 at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:230)
 at android.os.Looper.loop(Looper.java:319)
 at android.app.ActivityThread.main(ActivityThread.java:8893)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
 Suppressed: o9.f: [q1{Cancelling}@e14fc5c, Dispatchers.Main.immediate]
```

### Version

1.6.1

**Comment by chr56** [comment]
How to reproduce?

**Comment by chr56** [comment]
[v1.6.2](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.6.2) has been released!

Since I do not known how it was reproduced. I could not find its root cause. 
So I can only prevent it at surface.

Close! (Reopen if you meet it again.)
