### ISSUE TITLE
[Crash Report]  During animation from artist detail to overview activity

### ISSUE THREAD

**Issue by eku** [chr56/Phonograph_Plus#180]
### Crash log

```
Crash Report:

Package name:    player.phonograph.plus.preview
App version:     1.7-dev2 (1064)
Git Commit Hash: bdded970c85b7e40e640e3e0ccf7b130548650d1
Android version: 13 (SDK 33)
Device brand:    unknown  (by unknown)
Device model:    unknown (code: unknown)
Product name:    unknown
Build version:   unknown 
                 (20231214)
Hardware:        unknown
Language:        de


Stacktrace:
java.lang.NullPointerException
	at mf.d.h(SourceFile:5)
	at a0.h0.invoke(SourceFile:56)
	at mf.b.onAnimationEnd(SourceFile:12)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:600)
	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1086)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:307)
	at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(Unknown Source:0)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1313)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1323)
	at android.view.Choreographer.doCallbacks(Choreographer.java:956)
	at android.view.Choreographer.doFrame(Choreographer.java:863)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1298)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7941)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)
```

### Version

1.7-dev2

### Steps to reproduce the bug

Hard to reproduce. Sometimes it happens with the following sequence:

1. Choose artist tab
2. Tap on an artist with more than one album to change to artist detail view
3. Tap back to return to artist tab

### Environment

AOSP13

**Comment by eku** [comment]
It's an android tablet in landscape mode.

**Comment by chr56** [comment]
1. The number of albums does NOT matter, as I see so far. And any place where makes primary color change could cause such crash.
2. It is really hard to reproduce this crash, at least on my devises. Can you reproduce it stably?
3. Could you change Main Player Style to Flat, and check it again? Thank you very much!

**Comment by eku** [comment]
You are welcome. I will try to reproduce the error and check the situation.

**Comment by chr56** [comment]
This bug might be a resource leak of Animator for long time.

Try this one: [Phonograph_Preview_15c2dd41](https://github.com/chr56/Phonograph_Plus/files/15258369/Phonograph_PreviewRelease_15c2dd41.zip)

**Comment by chr56** [comment]
> I can no longer to reproduce this crash. I think it has been fixed.

[v1.7.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.7.0) released. Close!

Reopen or open a new Issue if you have more questions.
