### ISSUE TITLE
[Crash Report] Creating playlist

### ISSUE THREAD

**Issue by silbaer** [chr56/Phonograph_Plus#184]
### Crash log

```
Crash Report:

Package name:    player.phonograph.plus
App version:     1.6.3 (1063)
Git Commit Hash: f7efa61e7a0f7f81270e0b145e8caf75a0c325a9
Android version: 9 (SDK 28)
Device brand:    HONOR  (by HUAWEI)
Device model:    JSN-L21 (code: HWJSN-H)
Product name:    JSN-L21XEEA
Build version:   JSN-L21 9.1.0.312(C431E2R2P1) 
                 (9.1.0.312C431)
Hardware:        kirin710
Language:        de


Stacktrace:
java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/audio/playlists from pid=7235, uid=10128 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()
	at android.os.Parcel.createException(Parcel.java:1953)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
	at android.content.ContentResolver.insert(ContentResolver.java:1611)
	at n6.a.f1(SourceFile:78)
	at je.a.invokeSuspend(SourceFile:100)
	at je.a.invoke(SourceFile:13)
	at r9.a.e0(SourceFile:5)
	at o8.m.r1(SourceFile:74)
	at he.e.a(SourceFile:120)
	at he.b.a(SourceFile:34)
	at lf.e0.invokeSuspend(SourceFile:33)
	at v8.a.resumeWith(SourceFile:9)
	at m9.h0.run(SourceFile:92)
	at androidx.appcompat.widget.j.run(SourceFile:46)
	at s9.j.run(SourceFile:3)
	at s9.a.run(SourceFile:96)
	Suppressed: r9.f: [q1{Cancelling}@2bdfd1a, Dispatchers.IO]


```

### Version

1.6.3

### Steps to reproduce the bug

Create playlist. After entering name and taping "create" it is crashing

### Other helpful information

No crash on my other phone Samsung A52

**Comment by chr56** [comment]
Are you sure that you grant _Write External Storage Permission_ to Phonograph Plus?

**Comment by silbaer** [comment]
Yes, I checked before. I now removed the permission and grand again and now it works. Thanks!
