### ISSUE TITLE
[Crash Report] after restart android TV device

### ISSUE THREAD

**Issue by Dim7x0** [chr56/Phonograph_Plus#211]
### Crash log

Crash Report:

App version:     1.8.1 (1081)
Git Commit Hash: 1956a97a5c4760f3e7dacbc7fe828a784a941575
Package name:    player.phonograph.plus
Release favor:   legacyStable
Android version: 9 (API 28)
Architecture:    armeabi-v7a, armeabi
Soc:             amlogic/galilei
Device brand:    Amlogic (by MINIX)
Device model:    galilei/NEO U22-XJ (code galilei)
Build version:   20211105 - V008
                (20211105)
Language:        ru
Screen:          1016x1920 (dpi 213)
Permissions:     Storage(READ WRITE)

Stacktrace:
java.lang.IllegalStateException
   at android.media.MediaPlayer._getAudioSessionId(Native Method)
   at android.media.MediaPlayer.getAudioSessionId(MediaPlayer.java:2754)
   at qf.b.b(SourceFile:81)
   at qf.b.setNextDataSource(SourceFile:71)
   at qf.p.j(SourceFile:30)
   at qf.i.handleMessage(SourceFile:67)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loop(Looper.java:193)
   at android.os.HandlerThread.run(HandlerThread.java:65)

### Version

1.8.1

### Steps to reproduce the bug

if you reboot the device when the application is playing music, the device boots and automatically launches this application with an error

**Comment by chr56** [comment]
Fixed since commit ad96b0d8.

Actually, issues #211 #234 #255 are similar.

Now using [this preview release](https://github.com/user-attachments/files/18530478/PhonographPlus_Preview_AvoidRandomCrashesFromBackground.zip) may fix these problems.
