### ISSUE TITLE
[bug]App crash on my Android TV

### ISSUE THREAD

**Issue by KonkaTV514** [chr56/Phonograph_Plus#222]
### Crash log

```
Crash Report:

App version:     1.8.4 (1084)
Git Commit Hash: ff9861b5a23611e2a02b2b62eebc0f7dbd119bca
Package name:    player.phonograph.plus
Release favor:   legacyStable
Android version: 9 (API 28)
Architecture:    armeabi-v7a, armeabi
Soc:             bigfish/bigfish 
Device brand:    KONKA (by Hisilicon)
Device model:    KKHi3751V563/KONKA Android TV V563 (code KKHi3751V563)
Build version:   PPR1.180610.011 release-keys
                 (eng.wuyeku.20201104.115221)
Language:        zh
Memory:          287/978 [L]
Screen:          1080x1920 (dpi 240)
Permissions:     Storage(READ WRITE)


Stacktrace:
java.lang.RuntimeException: Unable to create service player.phonograph.service.MusicService: java.lang.SecurityException: Failed to find provider media for user 0; expected to find a valid ContentProvider for this authority
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3585)
	at android.app.ActivityThread.access$1300(ActivityThread.java:206)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1707)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6722)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.SecurityException: Failed to find provider media for user 0; expected to find a valid ContentProvider for this authority
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:779)
	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1972)
	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1961)
	at player.phonograph.service.MusicService.onCreate(SourceFile:772)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3573)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.content.ContentService.registerContentObserver(ContentService.java:340)
	at android.content.IContentService$Stub.onTransact(IContentService.java:76)
	at com.android.server.content.ContentService.onTransact(ContentService.java:262)
	at android.os.Binder.execTransact(Binder.java:731)



```

### Version

1.8.4

### Steps to reproduce the bug

1. Open app
2. App crash

### Environment

Android TV(9)

### Other helpful information

No media store.

**Comment by chr56** [comment]
Just after upgrading?

**Comment by KonkaTV514** [comment]
I'm first installation.
