### ISSUE TITLE
[Crash Report] App Crashed

### ISSUE THREAD

**Issue by TTTUUUIII** [chr56/Phonograph_Plus#226]
### Crash log

```
Crash Report:

App version:     1.8.4 (1084)
Git Commit Hash: ff9861b5a23611e2a02b2b62eebc0f7dbd119bca
Package name:    player.phonograph.plus
Release favor:   legacyStable
Android version: 14 (API 34)
Architecture:    arm64-v8a
Soc:             GS201/cheetah (by Google) 
Device brand:    google (by Google)
Device model:    cheetah/Pixel 7 Pro (code cheetah)
Build version:   AP2A.240905.003
                 (12231197)
Language:        en
Memory:          4509/11471 
Screen:          2169x1080 (dpi 420)
Permissions:     Storage(READ WRITE)


Stacktrace:
android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=player.phonograph.plus/player.phonograph.service.MusicService }: app is in background uid UidRecord{9a49a9a u0a349 TPSL bg:+1s477ms idle change:procstateprocadj procs:0 seq(1171131,1171002)} caps=-------
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1946)
	at android.app.ContextImpl.startService(ContextImpl.java:1901)
	at android.content.ContextWrapper.startService(ContextWrapper.java:827)
	at android.content.ContextWrapper.startService(ContextWrapper.java:827)
	at android.content.ContextWrapper.startService(ContextWrapper.java:827)
	at ah.j0.invoke(SourceFile:1366)
	at androidx.lifecycle.k1.h(SourceFile:23)
	at androidx.lifecycle.y.a(SourceFile:23)
	at androidx.lifecycle.z.i(SourceFile:325)
	at androidx.lifecycle.z.g(SourceFile:77)
	at androidx.lifecycle.z.f(SourceFile:15)
	at androidx.lifecycle.v0.d(SourceFile:27)
	at androidx.lifecycle.p0.onActivityPostStarted(SourceFile:10)
	at android.app.Activity.dispatchActivityPostStarted(Activity.java:1562)
	at android.app.Activity.performStart(Activity.java:9042)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4018)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:327)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:307)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:279)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
	Suppressed: pa.e: [m1{Cancelling}@e1c292, Dispatchers.Main.immediate]
```

### Version

1.8.4

### Steps to reproduce the bug

Just play music in the background.

### Environment

Android 14 on Pixel 7 Pro

### Screenshots or Screen recordings

<img src="https://github.com/user-attachments/assets/220c5a6f-eb1c-49aa-9955-e3f91059ab63" width="30%" />

**Comment by chr56** [comment]
How? How do you start it from background? It should not be, normally.

**Comment by chr56** [comment]
Is #207 existed on your device?

**Comment by chr56** [comment]
Here is [a simple workaround](https://github.com/user-attachments/files/17172024/Preview-BackgroundService.zip) which can avoid it but not fix it.
