### ISSUE TITLE
[Bug] Couldn't read row 2236, col 0 from CursorWindow

### ISSUE THREAD

**Issue by SpitFire-666** [chr56/Phonograph_Plus#239]
### Bug Summary

```
 Crash Report:

App version:     1.8.5 (1085)
Git Commit Hash: e40633fc5d79b8ade20c093a4b4f5a62bb50af24
Package name:    player.phonograph.plus
Release favor:   legacyStable
Android version: 9 (API 28)
Architecture:    arm64-v8a, armeabi-v7a, armeabi
Soc:             hi3660/VTR 
Device brand:    HUAWEI (by HUAWEI)
Device model:    VTR-L09/VTR-L09 (code HWVTR)
Build version:   VTR-L09 9.1.0.252(C346E4R1P8)
                 (252C346)
Language:        en
Memory:          1654/3715 
Screen:          1792x1080 (dpi 408)
Permissions:     Storage(READ WRITE)


Stacktrace:
java.lang.IllegalStateException: Couldn't read row 2236, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:538)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
	at android.database.CursorWrapper.getLong(CursorWrapper.java:127)
	at vf.x.d(SourceFile:9)
	at vf.x.b(SourceFile:14)
	at ng.o$a.loadDataSetImpl(SourceFile:14)
	at ng.l.invokeSuspend(SourceFile:55)
	at o9.a.resumeWith(SourceFile:9)
	at ha.g0.run(SourceFile:102)
	at androidx.recyclerview.widget.v.run(SourceFile:188)
	at oa.j.run(SourceFile:3)
	at oa.a.run(SourceFile:93)
	Suppressed: ma.e: [n1{Cancelling}@47167ce, Dispatchers.IO]


```

### Version

1.8.5

### Steps to reproduce the bug

Randomly occurred

**Comment by chr56** [comment]
How "randomly"? Did you remember where it happened, or what you are doing when it happened?

**Comment by SpitFire-666** [comment]
Only happened once that I know of, after I did a music sync to my phone (add new songs, remove others). Happy to chalk it up to a 'me' problem :)

**Comment by chr56** [comment]
I have no idea.
This may be device specific:


<details>
<summary>Recovered Stacktrace</summary>

It looks like it's not a _completed_ fault of me.

```

java.lang.IllegalStateException: Couldn't read row 2236, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
        at android.database.CursorWindow.nativeGetLong(Native Method)
        at android.database.CursorWindow.getLong(CursorWindow.java:538)
        at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
        at android.database.CursorWrapper.getLong(CursorWrapper.java:127)
        at player.phonograph.repo.mediastore.internal.ResolverKt.readSong(Resolver.kt:48)
        at player.phonograph.repo.mediastore.internal.ResolverKt.intoSongs(Resolver.kt:35)
        at player.phonograph.repo.mediastore.loaders.AlbumLoader.all(AlbumLoader.kt:18)
        at player.phonograph.repo.mediastore.MediaStoreAlbums.all(MediaStoreAlbums.kt:14)
        at player.phonograph.repo.loader.Albums.all(Loaders.kt)
        at player.phonograph.ui.fragments.pages.AlbumPage$AlbumPageViewModel.loadDataSetImpl(AlbumPage.kt:26)
        at player.phonograph.ui.fragments.pages.AbsDisplayPageViewModel$loadDataset$1.invokeSuspend(AbsDisplayPageViewModel.kt:38)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.java:113)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [n1{Cancelling}@47167ce, Dispatchers.IO]
```
</details>

**Comment by SpitFire-666** [comment]
Happy to close this off since i haven't seen the error for ages now 🤷
