### ISSUE TITLE
[Crash Report] Crash log popping up & since then no file can be played anymore

### ISSUE THREAD

**Issue by STPKITT** [chr56/Phonograph_Plus#255]
### Crash log

Hi,
the follwing crash report popped up, while the app wasn't even used, in fact IIRC it happened after a reboot of that smartphone. I can since playback no more file, only see them when browsing via the "files"-tab.

```
Crash Report:

App version:     1.8.5.1 (1085)
Git Commit Hash: d37a3b69c8c70fcc49693df53d9bd02dd33f775a
Package name:    player.phonograph.plus
Release favor:   modernStable
Android version: 9 (API 28)
Architecture:    arm64-v8a, armeabi-v7a, armeabi
Soc:             qcom/msm8952 
Device brand:    Sony (by Sony)
Device model:    suzu/Xperia X (code suzu)
Build version:   lineage_suzu-userdebug 9 PQ3A.190801.002 eng.chippa.20200722.140438 test-keys
                 (eng.chippa.20200722.140438)
Language:        de
Memory:          1200/2848 
Screen:          1776x1080 (dpi 480)
Permissions:     Storage(READ WRITE)


Stacktrace:
java.lang.NullPointerException
	at ag.j.run(SourceFile:14)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```

### Version

1.8.5.1 d37ab69

**Comment by STPKITT** [comment]
It's still exactly the same with app verion 1.9.0 (1090).
It seems to happen everytime when the flight mode is disabled while the app is not in use. The situation that no playback is possible afterwards though seems to happen seldom and I can't see a pattern for that.

**Comment by chr56** [comment]
It should be fixed since commit dfc80cc7.

Actually, issues #211 #234 #255 are similar.

Now using [this preview release](https://github.com/user-attachments/files/18530478/PhonographPlus_Preview_AvoidRandomCrashesFromBackground.zip) may fix these problems.

**Comment by STPKITT** [comment]
Thanks very much! I'll test it once the update has reached the F-Droid repo I installed from.
