### ISSUE TITLE
[Crash Report] Pressing "Next song" in the notification crashes the app if queue is empty

### ISSUE THREAD

**Issue by eomanis** [chr56/Phonograph_Plus#257]
### Crash log

```
Crash Report:

App version:     1.8.5.1 (1085)
Git Commit Hash: d37a3b69c8c70fcc49693df53d9bd02dd33f775a
Package name:    player.phonograph.plus
Release favor:   modernStable
Android version: 15 (API 35)
Architecture:    arm64-v8a, armeabi-v7a, armeabi
Soc:             Tensor/bluejay (by Google) 
Device brand:    google (by Google)
Device model:    bluejay/Pixel 6a (code bluejay)
Build version:   2024121200
                 (2024121200)
Language:        en
Memory:          591/5602 
Screen:          2205x1080 (dpi 420)
Permissions:     Storage(READ WRITE)


Stacktrace:
java.lang.ArithmeticException: divide by zero
	at g6.j.jumpForward(SourceFile:27)
	at zf.g.d(SourceFile:57)
	at ag.h.run(SourceFile:95)
	at android.os.Handler.handleCallback(Handler.java:991)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
```

### Version

1.8.5.1

### Steps to reproduce the bug

1. Open the app when it has no playback queue, or possibly manually clear the queue
2. Swipe down to show the smartphone's notifications
3. In Phonograph Plus' persistent notification, touch the "Next song" button

### Environment

GrapheneOS, Build number 2024121200

### Other helpful information

Phonograph Plus 1.8.5.1 from F-Droid from 2024-11-09

**Comment by chr56** [comment]
Confirmed. Theoretically, the notification _should_ be dismissed in this situation, no matter what settings is on.

**Comment by chr56** [comment]
Temporary workaround is available since 07ef060a: 
[PhonographPlus-Preview-Channel-07ef060a](https://github.com/user-attachments/files/18221131/PhonographPlus-07ef060a.zip)

**Comment by chr56** [comment]
[v1.9.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.9.0) has been released! 
close!
