### ISSUE TITLE
[Crash Report] App crashes when reordering playlist

### ISSUE THREAD

**Issue by dossma** [chr56/Phonograph_Plus#259]
### Crash log

```
Crash Report:

App version:     1.8.5.1 (1085)
Git Commit Hash: d37a3b69c8c70fcc49693df53d9bd02dd33f775a
Package name:    player.phonograph.plus
Release favor:   modernStable
Android version: 15 (API 35)
Architecture:    arm64-v8a
Soc:             Tensor G3/shiba (by Google) 
Device brand:    google (by Google)
Device model:    shiba/Pixel 8 (code shiba)
Build version:   2024121200
                 (2024121200)
Language:        de
Memory:          1434/7353 
Screen:          2205x1080 (dpi 420)
Permissions:     Storage(READ WRITE)


Stacktrace:
java.lang.IllegalArgumentException: Failed to resolve playlist member Bundle[{android:query-arg-sql-selection=play_order=7}]
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:155)
	at android.content.ContentProviderProxy.update(ContentProviderNative.java:685)
	at android.content.ContentResolver.update(ContentResolver.java:2444)
	at android.content.ContentResolver.update(ContentResolver.java:2406)
	at android.provider.MediaStore$Audio$Playlists$Members.moveItem(MediaStore.java:3883)
	at hf.e.invokeSuspend(SourceFile:18)
	at hf.e.invoke(SourceFile:13)
	at ea.m.V(SourceFile:5)
	at ha.z.C(SourceFile:78)
	at ff.c.c(SourceFile:19)
	at tg.v.moveItem(SourceFile:58)
	at tg.m0.invokeSuspend(SourceFile:37)
	at tg.m0.invoke(SourceFile:13)
	at ea.m.V(SourceFile:5)
	at ha.z.C(SourceFile:78)
	at tg.o0.j(SourceFile:87)
	at tg.n0.invokeSuspend(SourceFile:33)
	at o9.a.resumeWith(SourceFile:9)
	at ha.g0.run(SourceFile:102)
	at androidx.recyclerview.widget.v.run(SourceFile:188)
	at oa.j.run(SourceFile:3)
	at oa.a.run(SourceFile:93)
	Suppressed: ma.e: [n1{Cancelling}@595d96c, Dispatchers.IO]
```

### Version

1.8.5.1

### Steps to reproduce the bug

I have a playlist where attempts to reorder songs result always in a crash. Thus, I'm practically unable to reorder this playlist. For some songs or playlist positions (unable to say which one) it works. 

Additionally, I am unable to remove **any** song from this playlist. For all songs in this playlist it seems like, after tapping "remove from playlist" in edit mode, nothing happens. In other playlists it works to remove songs. 

### Other helpful information

The playlist is called `drums.m3u` and is in no other folder than the other playlists.

**Comment by chr56** [comment]
1. discussion of reproducibility

> For some songs or playlist positions (unable to say which one) it works.

So, this crash only happens for _only_ some playlists or some positions in a playlist? And currently you can not locate them or find the pattern.

2. discussion of compatibility

Before upgrading to Android 15, is this problem existed? (Ignore this one if it's not applicable for you, like starting using application these days)

3. suggestion

In [v1.9.0-dev2](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.9.0-dev2), we prevented the crash but not fixed (No effects instead of causing crash if it fails)

**Comment by dossma** [comment]
> 1. discussion of reproducibility
> 
> 
> > For some songs or playlist positions (unable to say which one) it works.
> 
> So, this crash only happens for _only_ some playlists or some positions in a playlist? And currently you can not locate them or find the pattern.

This behavior was observed in only one playlist. If I add songs where reordering always crashes (see second video) to another playlist, reordering works there without issue. I made two screen recordings for you. See [here](https://k00.fr/sxjnou6m) and [here](https://k00.fr/za8h7zp3). 

That I cannot delete entries looks like is happening only in this playlist as well. This doesn't result in a crash but instead there is no reaction after tapping to remove it.

>     2. discussion of compatibility
> 
> 
> Before upgrading to Android 15, is this problem existed? (Ignore this one if it's not applicable for you, like starting using application these days)

Not applicable

> 
>     3. suggestion
> 
> 
> In [v1.9.0-dev2](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.9.0-dev2), we prevented the crash but not fixed (No effects instead of causing crash if it fails)

**Comment by chr56** [comment]
I strongly recommend you to install Preview Channel v1.9.0-dev2. I could **only** reproduce the crash on v1.8.5.1 sometimes.
