### ISSUE TITLE
[Bug Report] Can not save tags and images

### ISSUE THREAD

**Issue by uli-on** [chr56/Phonograph_Plus#35]
**Describe the bug or unexpected behavior**
Errors appear on editing artist images and tracks' tags. Remarkable seems that at least one time an error on image allocation was admonished while no image was on screen, simply editing tags, see my annotation with "heads up". 
Sorry in case I posted duplicates, better than leaving out hints, I assume. 

**Crash log**
```
[Crash Report:

Package name:    player.phonograph.plus
App version:     0.3.4 (312)
Git Commit Hash: b6ce5aaed1b0c9c0c156
Android version: 10 (SDK 29)
Device brand:    Fairphone  (by Fairphone)
Device model:    FP3 (code: FP3)
Product name:    FP3
Build version:   8901.3.A.0136 
                 (gms-7c69ec7e)
Hardware:        qcom
Language:        de

No Songs Modified!? Maybe fail save tags?
java.lang.IllegalStateException: No Songs Modified!?
	at util.phonograph.tageditor.h.invokeSuspend(Unknown Source:75)
	at o3.a.resumeWith(Unknown Source:8)
	at f4.m0.run(Unknown Source:102)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
}

-------------------


Crash Report:

Package name:    player.phonograph.plus
App version:     0.3.4 (312)
Git Commit Hash: b6ce5aaed1b0c9c0c156
Android version: 10 (SDK 29)
Device brand:    Fairphone  (by Fairphone)
Device model:    FP3 (code: FP3)
Product name:    FP3
Build version:   8901.3.A.0136 
                 (gms-7c69ec7e)
Hardware:        qcom
Language:        de

No Songs Modified!? Maybe fail save tags?
java.lang.IllegalStateException: No Songs Modified!?
	at util.phonograph.tageditor.h.invokeSuspend(Unknown Source:75)
	at o3.a.resumeWith(Unknown Source:8)
	at f4.m0.run(Unknown Source:102)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
}

------------------


Crash Report:

Package name:    player.phonograph.plus
App version:     0.3.4 (312)
Git Commit Hash: b6ce5aaed1b0c9c0c156
Android version: 10 (SDK 29)
Device brand:    Fairphone  (by Fairphone)
Device model:    FP3 (code: FP3)
Product name:    FP3
Build version:   8901.3.A.0136 
                 (gms-7c69ec7e)
Hardware:        qcom
Language:        de

Can not save custom image for Goldfrapp

------------

HEADS UP: FOLLOWING CAME UP ON SAVING TAGS, NOT IMAGE


Crash Report:

Package name:    player.phonograph.plus
App version:     0.3.4 (312)
Git Commit Hash: b6ce5aaed1b0c9c0c156
Android version: 10 (SDK 29)
Device brand:    Fairphone  (by Fairphone)
Device model:    FP3 (code: FP3)
Product name:    FP3
Build version:   8901.3.A.0136 
                 (gms-7c69ec7e)
Hardware:        qcom
Language:        de

Can not save custom image for Goldfrapp

```

**Comment by chr56** [comment]
**Do not use tag editor**, it is **not under maintenance** and **deprecated** actually and **dangerous** for causing existing tags loss!!

Until I write a brand new tag editor (about at beginning of next year), do not use it, and report it because I won't fix them.

**Comment by uli-on** [comment]
OK, understood. Feel free to do with this topic what you think is appropriate, rename, close, leave for visibility reasons ...

**Comment by chr56** [comment]
Finally, [preview_0.6.0-dev2](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_0.6.0-dev2) has been released.

New tag editors replaced those deprecated & legacy ones.

This issue wound be closed when stable is ready.

**Comment by uli-on** [comment]
Thanks :)

Unfortunately adding an image to the tagging dialogue gives the following
error on my phone on saving, although I've granted the desired privileges:

-----------------------------

```Internal Error:

Package name:    player.phonograph.plus.preview
App version:     0.6.0-dev2 (461)
Git Commit Hash: ce27e77ed39b14dbeb8c
Android version: 10 (SDK 29)
Device brand:    Fairphone  (by Fairphone)
Device model:    FP3 (code: FP3)
Product name:    FP3
Build version:   8901.3.A.0136
                 (gms-7c69ec7e)
Hardware:        qcom
Language:        de

Failed to write tag!
z8.b: z8.g: Cannot modify 30-70 Collective - Elevate - 09 Misrepresented
(Radio Edit).mp3 because do not have permissions to create files in the
folder /storage/3366-3661/Music/30-70 Collective
	at e9.b.b(Unknown Source:14)
	at xb.b.applyEditImpl(SourceFile:115)
	at xb.c$a.invokeSuspend(Unknown Source:32)
	at k6.a.resumeWith(Unknown Source:8)
	at b7.r0.run(Unknown Source:102)
	at kotlinx.coroutines.internal.i.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a$a.run(SourceFile:63)
Caused by: z8.g: Cannot modify 30-70 Collective - Elevate - 09
Misrepresented (Radio Edit).mp3 because do not have permissions to create
files in the folder /storage/3366-3661/Music/30-70 Collective
	at org.jaudiotagger.tag.id3.AbstractID3v2Tag.c0(SourceFile:841)
	at org.jaudiotagger.tag.id3.ID3v23Tag.Z(Unknown Source:185)
	at e9.b.m(SourceFile:167)
	at e9.b.b(Unknown Source:0)
	... 7 more
}
```

**Comment by chr56** [comment]
OK, it is _confirmed_ and _reproduced_.

The problem is about the permission to **external**(or "**physical**") sdcard.

This temporary workaround is: **Move the song to internal storage.**

I would try to ask permission to external sdcard before writing files in next version.

PS:
external sdcard path is like `/storage/<4 digit or letter>-<4 digit or letter>/…`
internal storage (emulated sdcard) path is like `/storage/emulated/0/…`

**Comment by uli-on** [comment]
From files in internal storage I got:

Internal Error:

Package name:    player.phonograph.plus.preview
App version:     0.6.0-dev2 (461)
Git Commit Hash: ce27e77ed39b14dbeb8c
Android version: 10 (SDK 29)
Device brand:    Fairphone  (by Fairphone)
Device model:    FP3 (code: FP3)
Product name:    FP3
Build version:   8901.3.A.0136
                 (gms-7c69ec7e)
Hardware:        qcom
Language:        de

Failed to write tag!
z8.a: No Reader associated with this extension:m4a
	at r8.b.a(SourceFile:116)
	at xb.b.applyEditImpl(SourceFile:91)
	at xb.e$a.invokeSuspend(Unknown Source:15)
	at k6.a.resumeWith(Unknown Source:8)
	at b7.r0.run(Unknown Source:102)
	at kotlinx.coroutines.internal.i.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a$a.run(SourceFile:63)
}

**Comment by chr56** [comment]
Well, then just m4a is currently unsupported, sorry.

**Comment by uli-on** [comment]
OK, so now I copied an mp3 over to the internal storage (remember, permissions already granted) and I get

```
Internal Error:

Package name:    player.phonograph.plus.preview
App version:     0.6.0-dev2 (461)
Git Commit Hash: ce27e77ed39b14dbeb8c
Android version: 10 (SDK 29)
Device brand:    Fairphone  (by Fairphone)
Device model:    FP3 (code: FP3)
Product name:    FP3
Build version:   8901.3.A.0136 
                 (gms-7c69ec7e)
Hardware:        qcom
Language:        de

Failed to write tag!
z8.b: z8.g: Cannot modify 01 Collapsed in Sunbeams.mp3 because do not have permissions to create files in the folder /storage/emulated/0/Music
	at e9.b.b(Unknown Source:14)
	at xb.b.applyEditImpl(SourceFile:115)
	at xb.c$a.invokeSuspend(Unknown Source:32)
	at k6.a.resumeWith(Unknown Source:8)
	at b7.r0.run(Unknown Source:102)
	at kotlinx.coroutines.internal.i.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a$a.run(SourceFile:63)
Caused by: z8.g: Cannot modify 01 Collapsed in Sunbeams.mp3 because do not have permissions to create files in the folder /storage/emulated/0/Music
	at org.jaudiotagger.tag.id3.AbstractID3v2Tag.c0(SourceFile:841)
	at org.jaudiotagger.tag.id3.ID3v23Tag.Z(Unknown Source:185)
	at e9.b.m(SourceFile:167)
	at e9.b.b(Unknown Source:0)
	... 7 more
}
```

**Comment by chr56** [comment]
Sorry, I could not figure out where exactly goes wrong. 

Sadly, "everything works fine for me". I am afraid that the bug might not be fixed in v0.6.0, and maybe exist util I found the solution.
