### ISSUE TITLE
Crash when clicking "Lyrics Following"

### ISSUE THREAD

**Issue by Accumulation142857** [chr56/Phonograph_Plus#49]
### Crash log

Crash Report:

Package name:    player.phonograph.plus
App version:     0.5.0 (450)
Git Commit Hash: 13b4722d48f77ccf81dd
Android version: 12 (SDK 31)
Device brand:    motorola  (by motorola)
Device model:    XT2225-2 (code: rhodep)
Product name:    rhodep_cn
Build version:   S1SU32.73-112-4 
                 (e8b769-403a5)
Hardware:        qcom
Language:        zh

java.lang.IllegalArgumentException: Invalid target position
	at androidx.recyclerview.widget.RecyclerView$x.l(SourceFile:104)
	at androidx.recyclerview.widget.RecyclerView$m.O0(Unknown Source:21)
	at androidx.recyclerview.widget.LinearLayoutManager.N0(Unknown Source:12)
	at player.phonograph.dialogs.LyricsDialog.onUpdateProgressViews(SourceFile:33)
	at ma.a.handleMessage(SourceFile:31)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8089)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

### Steps to reproduce the bug

点击“歌词滚动”

### Screenshots or Screen recordings

![Screenshot_20221207-004747](https://user-images.githubusercontent.com/119960445/205973094-4a167712-bc97-443b-a9ab-1126c72f19ab.png)

### Version

 0.5.0

**Comment by chr56** [comment]
lrc歌词文件发发一下？
播放到哪个位置崩的？

**Comment by Accumulation142857** [comment]
音乐是flac格式，音乐标签内嵌歌词。只要点击“歌词滚动”，无论播放到哪个位置，软件都会崩溃。
![Screenshot_20221208-133827](https://user-images.githubusercontent.com/119960445/206365508-6aa8176a-d0fe-4856-bdf9-549cbf04a9ca.png)

**Comment by chr56** [comment]
> 音乐是flac格式，音乐标签内嵌歌词。

那有可能是flac标签格式问题；现在flac标签支持不太好...

等我再看看...

**Comment by chr56** [comment]
看了一下，<del>感觉没问题啊</del>

也拿了flac试了一下，也<del>没问题啊</del>

可能是标签问题？
