### ISSUE TITLE
[Bug]: Crash during playback, Animator already started

### ISSUE THREAD

**Issue by dominikheinz** [chr56/Phonograph_Plus#51]
### Bug Summary

During song playback, I sometimes (seemingly random) have Phonograph Plus crash. I am using a Pixel 6, running GrapheneOS.

This is the crashlog:

```
Crash Report:

Package name:    player.phonograph.plus
App version:     0.5.0 (450)
Git Commit Hash: 13b4722d48f77ccf81dd
Android version: 13 (SDK 33)
Device brand:    google  (by Google)
Device model:    Pixel 6 (code: oriole)
Product name:    oriole
Build version:   TQ1A.221205.011.2022122000 
                 (2022122000)
Hardware:        oriole
Language:        en

java.lang.IllegalStateException: Animator has already started, cannot change it now!
	at android.graphics.animation.RenderNodeAnimator.checkMutable(RenderNodeAnimator.java:138)
	at android.graphics.animation.RenderNodeAnimator.setDuration(RenderNodeAnimator.java:314)
	at android.graphics.animation.RenderNodeAnimator.setDuration(RenderNodeAnimator.java:37)
	at android.animation.AnimatorSet.updateAnimatorsDuration(AnimatorSet.java:774)
	at android.animation.AnimatorSet.getTotalDuration(AnimatorSet.java:1744)
	at android.animation.AnimationHandler.lambda$new$0$android-animation-AnimationHandler(AnimationHandler.java:224)
	at android.animation.AnimationHandler$$ExternalSyntheticLambda0.doFrame(Unknown Source:2)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:827)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7878)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
```

### Version

0.5.0

### Steps to reproduce the bug

Unclear, appears randomly during song playback, usually pretty quickly after the song is clicked on for playback (in the first couple seconds)

### Environment

OS: GrapheneOS
Device: Pixel 6

**Comment by chr56** [comment]
Because the reported stacktrace is on the thread that I am not controlled, I am not sure where the actual problem is. I guess it might be the color-change animation in main player ui, so I do the precaution to avoid to start animation twice or more.

Try [v0.5.1](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.5.1).

**Comment by chr56** [comment]
Try [v0.5.4](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.5.4).
Now player should not crash by color-change animation now.

**Comment by dominikheinz** [comment]
Seems fixed. Thank You!

**Comment by bgaesslein** [comment]
@chr56 could you perhaps give me a hint as to what you changed to fix this issue, specifically? I'm experiencing this exact error on a different Phonograph-based app. I would appreciate it. :)

**Comment by chr56** [comment]
> @chr56 could you perhaps give me a hint as to what you changed to fix this issue, specifically? I'm experiencing this exact error on a different Phonograph-based app. I would appreciate it. :)
> 
> Edit: it's commit [013af99](https://github.com/chr56/Phonograph_Plus/commit/013af99ecd5e0ddeeaa346b7dc3e556e1410b72b), right? I'll try if I this will fix it in Gelli, too.

Sorry, I forget. 😂

I only remember I used Lifecycle with kotlin Coroutine or some what to ultimately fix this.

**Comment by chr56** [comment]
013af99ecd5e is definitely **NOT** what you are looking for.

@bgaesslein

**Comment by bgaesslein** [comment]
Thanks for the reply. :) No problem, I'll try to figure it out. Figured it was worth a shot.

**Comment by chr56** [comment]
It looks that it's 623029a, no Lifecycle involved. Just cancel the previous one before start. I am not sure whether I eventually fixed it or not.

**Comment by bgaesslein** [comment]
Thank you very much, I will try if that fixes it.

**Comment by chr56** [comment]
> Thank you very much, I will try if that fixes it.

No, that doesn't work either. Sorry.😅

It's b6701819005ab7dc4a9eddb83f86d41948a9246d: Use `Lifecycle` to check current state, and return `animateColorChange()` if not at least `Lifecycle.State.RESUMED`

@bgaesslein 

BTW, 013af99ecd5e0ddeeaa346b7dc3e556e1410b72b is my problem: the issue only in Phonograph Plus due to new mechanism about night mode detection, it is not working for you.
