### ISSUE TITLE
[Bug]: Album Art not showing 

### ISSUE THREAD

**Issue by DraconicNEO** [chr56/Phonograph_Plus#52]
### Bug Summary

When I open the app none of my songs display the album art despite most of them having Album art in their tag.

### Version

0.5.0 

### Steps to reproduce the bug

Download the app and install it like new, open the app for the first time go through setup and none of the songs will have album art.

### Environment

Android 9

MIUI 10.3.2

**Comment by chr56** [comment]
[v0.5.2](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.5.2) has released.
Go to `Setting -> Images -> Image Source Config` to turn off some of them or reorder them, this might help.

**Comment by DraconicNEO** [comment]
> [v0.5.2](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.5.2) has released. Go to `Setting -> Images -> Image Source Config` to turn off some of them or reorder them, this might help.

When I tried to reorder them the order list wouldn't save the new positions, they would always just revert back to what they were before. I also tried turning off certain items and turning on others but so far it seems none of them allow the Album art to display.

**Comment by SamuelMezger** [comment]
Hi, for me the album art reappears if I disable both `Android MediaStore` and `Android Media Metadata Retriever`. Reordering does not work reliably for me as well.

If `Android MediaStore` is enabled I get the following error:
```
W/System.err: java.io.IOException: Stream Closed
W/System.err:     at java.io.FileInputStream.read(FileInputStream.java:246)
W/System.err:     at android.os.ParcelFileDescriptor$AutoCloseInputStream.read(ParcelFileDescriptor.java:889)
W/System.err:     at okio.InputStreamSource.read(JvmOkio.kt:94)
W/System.err:     at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
W/System.err:     at okio.ForwardingSource.read(ForwardingSource.kt:27)
W/System.err:     at coil.decode.BitmapFactoryDecoder$ExceptionCatchingSource.read(BitmapFactoryDecoder.kt:215)
W/System.err:     at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
W/System.err:     at okio.PeekSource.read(PeekSource.kt:50)
W/System.err:     at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
W/System.err:     at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
W/System.err:     at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:646)
W/System.err:     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:622)
W/System.err:     at coil.decode.BitmapFactoryDecoder.decode(BitmapFactoryDecoder.kt:55)
W/System.err:     at coil.decode.BitmapFactoryDecoder.access$decode(BitmapFactoryDecoder.kt:25)
W/System.err:     at coil.decode.BitmapFactoryDecoder$decode$2$1.invoke(BitmapFactoryDecoder.kt:46)
W/System.err:     at coil.decode.BitmapFactoryDecoder$decode$2$1.invoke(BitmapFactoryDecoder.kt:46)
W/System.err:     at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
W/System.err:     at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
W/System.err:     at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
W/System.err:     at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invoke(Interruptible.kt)
W/System.err:     at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invoke(Interruptible.kt)
W/System.err:     at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
W/System.err:     at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:161)
W/System.err:     at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
W/System.err:     at kotlinx.coroutines.InterruptibleKt.runInterruptible(Interruptible.kt:42)
W/System.err:     at kotlinx.coroutines.InterruptibleKt.runInterruptible$default(Interruptible.kt:39)
W/System.err:     at coil.decode.BitmapFactoryDecoder.decode(BitmapFactoryDecoder.kt:46)
W/System.err:     at coil.intercept.EngineInterceptor.decode(EngineInterceptor.kt:199)
W/System.err:     at coil.intercept.EngineInterceptor.access$decode(EngineInterceptor.kt:41)
W/System.err:     at coil.intercept.EngineInterceptor$execute$executeResult$1.invokeSuspend(EngineInterceptor.kt:127)
W/System.err:     at coil.intercept.EngineInterceptor$execute$executeResult$1.invoke(EngineInterceptor.kt)
W/System.err:     at coil.intercept.EngineInterceptor$execute$executeResult$1.invoke(EngineInterceptor.kt)
W/System.err:     at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
W/System.err:     at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
W/System.err:     at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
W/System.err:     at coil.intercept.EngineInterceptor.execute(EngineInterceptor.kt:126)
W/System.err:     at coil.intercept.EngineInterceptor.access$execute(EngineInterceptor.kt:41)
W/System.err:     at coil.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.kt:75)
W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
W/System.err:     at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
W/System.err:     at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

If `Android MediaStore` is disabled and `Android Media Metadata Retriever` is enabled it seems to fail silently while trying to use the `MediaMetadataRetriever` [here](https://github.com/chr56/Phonograph_Plus/blob/1d0cc432f2d1fae8e2bcf500226b43ef22fbeca0/app/src/main/java/player/phonograph/coil/retriever/ImageRetriever.kt#L46).

**Comment by chr56** [comment]
_(If you are still using Phonograph Plus, please read or ignore this comment)_


This problem (related with log you grabbed) should be fixed in this Preview below (at least fixed on my old Android N device).

[PhonographPlus_image_fix.zip](https://github.com/chr56/Phonograph_Plus/files/13848791/PhonographPlus_image_fix.zip)

**Comment by chr56** [comment]
[v1.4.3](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.4.3) has been released! This (referred in logs) should be fixed! Close!
