### ISSUE TITLE
[Crash Report]: cant play SD card. "open with" crash loop

### ISSUE THREAD

**Issue by 1sad** [chr56/Phonograph_Plus#59]
### Crash log

```
Crash Report:

Package name:    player.phonograph.plus
App version:     0.5.4.1 (454)
Git Commit Hash: 121a4b440d10ed7d2321
Android version: 10 (SDK 29)
Device brand:    Redmi  (by Xiaomi)
Device model:    M2004J19C (code: galahad)
Product name:    galahad_global
Build version:   build-20210331141959 
                 (V12.0.4.0.QJCMIXM)
Hardware:        mt6768
Language:        en

java.lang.RuntimeException: Unable to start activity ComponentInfo{player.phonograph.plus/player.phonograph.ui.activities.StarterActivity}: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3338)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3487)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:224)
    at android.app.ActivityThread.main(ActivityThread.java:7561)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.get(ArrayList.java:437)
    at player.phonograph.ui.activities.StarterActivity$b.d(SourceFile:154)
    at player.phonograph.ui.activities.StarterActivity.onCreate(SourceFile:52)
    at android.app.Activity.performCreate(Activity.java:7893)
    at android.app.Activity.performCreate(Activity.java:7880)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3313)
    ... 11 more
```

### Steps to reproduce the bug

use file manager
click on song
open with phonograph
crashloop

### Other helpful information

it crashes so hard cant even uninstall the app anymore without rebooting the phone
cant add or play any files from SD card on any settings at all.

edit: 
after 3 reboots it suddenly stopped crashing and adding SD songs just works now?..
except when i "open with" song from file manager it loops the "Couldn't play song" error

need more testing but i guess this log could be useful?

**Comment by chr56** [comment]
_(If you are still using Phonograph Plus, please)_
Try this revision:
[PhonographPlusPreview_24ff05d5f.zip](https://github.com/chr56/Phonograph_Plus/files/14018360/PhonographPlusPreview_24ff05d5f.zip)

And Excuse me, can you tell me which file manager you are using?

**Comment by 1sad** [comment]
the preview version crashes when i try, and hard to uninstall it too.

1.4.3 version from f-droid works with "Fossify File Manager" it pops up the 4 choice menu, but only adds it to the playlist paused when i choose "play song right now". with "Material Files" it shows like this ![Screenshot_2024-01-23-20-45-00-182_player phonograph plus](https://github.com/chr56/Phonograph_Plus/assets/23120024/abacd9ef-d928-42bc-bedb-2941e7121443)

and with android stock doccuments ui it was working at first, but when i installed the preview build and now uninstalled it its showing me the same empty thing. even after rebooting and reinstalling the fdroid version. but at least app isnt crashing.
i was not using the app for a while. still troubles with properly uninstalling it, need to go to different menus to do it.

**Comment by chr56** [comment]
Thank you for your feedback.
Please test with previous versions only.

As you described:
1) Stock Doccuments: working
2) Fossify File Manager: working
3) Material Files: not working

Is that right?

-------
Also, Preview version [v1.4.4-dev1](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.4.4-dev1) has been released! 
This contains the same fix in the previous I send.

**Comment by 1sad** [comment]
**PhonographPlusPreview_24ff05d5f.zip**
does not work, crashing




**version 1.4.3 f-droid**
no crashing but:
   1 Stock Doccuments: was working at first, not working anymore 🤷 (shows empty like the picture) 
   2 Fossify File Manager: working 👍 
   3 Material Files: not working (shows empty like the picture) 
![image](https://github.com/chr56/Phonograph_Plus/assets/23120024/68f8faa3-2ee1-4850-9c4c-afff2f82c867)




**PhonographPlus_1.4.4-dev1.apk** 
   1 Stock Doccuments: crashing

```
Crash Report:

Package name: player.phonograph.plus.preview
App version: 1.4.4-dev1 (1043)
Git Commit Hash: 943474b45d52f8051e2a36a166fa762feef70d27
Android version: 11 (SDK 30)
Device brand: Redmi (by Xiaomi)
Device model: M2004J19C (code: galahad)
Product name: galahad_global
Build version: RP1A.200720.011
(V12.5.6.0.RJCMIXM)
Hardware: mt6768
Language: en

Stack Track:
java.lang.RuntimeException: Unable to start activity ComponentInfo{player.phonograph.plus.preview/player.phonograph.ui.activities.StarterActivity}: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{81713f4 13811:player.phonograph.plus.preview/u0a732} (pid=13811, uid=10732) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3520)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3692)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThreadH.handleMessage(ActivityThread.java:2142)MethodAndArgsCaller.run(RuntimeInit.java:620)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{81713f4 13811:player.phonograph.plus.preview/u0a732} (pid=13811, uid=10732) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
at android.os.Parcel.createException(Parcel.java:2360)
at android.os.Parcel.readException(Parcel.java:2343)
at android.os.Parcel.readException(Parcel.java:2285)
at android.app.IActivityManagerStubProxy.getContentProvider(IActivityManager.java:5983)
at android.app.ActivityThread.acquireProvider(ActivityThread.java:6974)
at android.app.ContextImplApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2958)Stub.onTransact(IActivityManager.java:2509)
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3002)
at android.os.Binder.execTransactInternal(Binder.java:1154)
```



   2 Fossify File Manager: shows dialog > then crashing (when i select option and press OK)
![image](https://github.com/chr56/Phonograph_Plus/assets/23120024/95f370aa-b42c-4fe8-8d2b-bcb808cd02c4)

```
Crash Report:

Package name: player.phonograph.plus.preview
App version: 1.4.4-dev1 (1043)
Git Commit Hash: 943474b45d52f8051e2a36a166fa762feef70d27
Android version: 11 (SDK 30)
Device brand: Redmi (by Xiaomi)
Device model: M2004J19C (code: galahad)
Product name: galahad_global
Build version: RP1A.200720.011
(V12.5.6.0.RJCMIXM)
Hardware: mt6768
Language: en

Stack Track:
java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
at java.util.concurrent.CopyOnWriteArrayList.add(CopyOnWriteArrayList.java:449)
at mc.w.a(SourceFile:56)
at mc.w.invoke(SourceFile:21)
at mc.d.m(SourceFile:1)
at mc.i.a(SourceFile:189)
at mc.i.invoke(SourceFile:17)
at mc.j.run(SourceFile:63)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:236)
at android.os.HandlerThread.run(HandlerThread.java:67)
````



3 Material Files: not working (shows empty like the picture) 
![image](https://github.com/chr56/Phonograph_Plus/assets/23120024/68f8faa3-2ee1-4850-9c4c-afff2f82c867)

**Comment by chr56** [comment]
Well, for **version 1.4.4-dev1**:

1 and 3 may be caused by permissions, have you grant enough storage access permission? (Tips: `Main Drawer` -> `More` -> `Grant External Storage Permission`).
2 is caused due to adding something into empty playing queue.

-------------------------

This Preview revision would fix problem 2.
[PhonographPlusPreview_fa7aa5a0.zip](https://github.com/chr56/Phonograph_Plus/files/14072676/PhonographPlusPreview_fa7aa5a0.zip)

**Comment by chr56** [comment]
Stable Release [v1.4.4](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.4.4) has been released!

Is problem solved?

**Comment by 1sad** [comment]
still broken in 1.4.4

I granted the permission from "more"

stock android:
```Crash Report:

Package name:    player.phonograph.plus
App version:     1.4.4 (1044)
Git Commit Hash: fed2dee21d07a2a65d48959249b44abecf671768
Android version: 11 (SDK 30)
Device brand:    Redmi  (by Xiaomi)
Device model:    M2004J19C (code: galahad)
Product name:    galahad_global
Build version:   RP1A.200720.011 
                 (V12.5.6.0.RJCMIXM)
Hardware:        mt6768
Language:        en


Stack Track:
java.lang.RuntimeException: Unable to start activity ComponentInfo{player.phonograph.plus/player.phonograph.ui.activities.StarterActivity}: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{2d2d0dc 7828:player.phonograph.plus/u0a728} (pid=7828, uid=10728) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3520)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3692)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2142)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7864)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{2d2d0dc 7828:player.phonograph.plus/u0a728} (pid=7828, uid=10728) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
	at android.os.Parcel.createException(Parcel.java:2360)
	at android.os.Parcel.readException(Parcel.java:2343)
	at android.os.Parcel.readException(Parcel.java:2285)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5983)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6974)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2958)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2506)
	at android.content.ContentResolver.query(ContentResolver.java:1179)
	at android.content.ContentResolver.query(ContentResolver.java:1127)
	at android.content.ContentResolver.query(ContentResolver.java:1083)
	at sd.a.parse(SourceFile:22)
	at player.phonograph.ui.activities.StarterActivity.onCreate(SourceFile:299)
	at android.app.Activity.performCreate(Activity.java:8109)
	at android.app.Activity.performCreate(Activity.java:8083)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3493)
	... 11 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:7535)
	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:8010)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2509)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3002)
	at android.os.Binder.execTransactInternal(Binder.java:1159)


```

material files: 
pops up a "can't play this file [filepath]" message

maybe something  is wrong with my phone?.. can't attach image in cromite to github

**Comment by 1sad** [comment]
I turned on miui optimization and it started working...  🤦 
but there is another issue I found, chosing "play now (add to top)" makes it look like the new file is playing, cover art and name changes, but old file is still playing. and after the song finishes it just repeats, never playing the new added file
