### ISSUE TITLE
[Bug] Failed to read song file  y8.a: /storage/emulat......

### ISSUE THREAD

**Issue by anaskaejdar** [chr56/Phonograph_Plus#61]
Good morning! I'm just leaving these error reports here. Lately, I get a LOT of these error reports. The file does play despite the errors.

![Screenshot_۲۰۲۳۰۳۰۱_۰۷۰۶۴۴_Mull](https://user-images.githubusercontent.com/32847759/222164941-a1e4c5bb-310d-4281-84cb-7358adff1a39.jpg)

```
Internal Error:

Package name:    player.phonograph.plus
App version:     0.5.4 (454)
Git Commit Hash: 52f6af7552aa0d623bf1
Android version: 13 (SDK 33)
Device brand:    samsung  (by samsung)
Device model:    SM-S908U (code: b0q)
Product name:    b0qsqw
Build version:   TP1A.220624.014.S908USQU2CWAI 
                 (S908USQU2CWAI)
Hardware:        qcom
Language:        fa

Failed to read song file

y8.a: /storage/emulated/0/Music/Psalticí/Dimitrios Katsiklis/Θεία Λειτουργία σε Πλάγιο Πρώτο-KIw7eo_yyp4.m4a:java.lang.NoSuchMethodException: ba.r.<init> [class ba.w]
	at b9.d.c(Unknown Source:161)
	at q8.b.a(SourceFile:96)
	at wa.g.a(Unknown Source:3)
	at wa.g$c.invokeSuspend(Unknown Source:12)
	at k6.a.resumeWith(Unknown Source:8)
	at b7.r0.run(Unknown Source:102)
	at kotlinx.coroutines.internal.i.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a$a.run(SourceFile:66)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: ba.r.<init> [class ba.w]
	at b9.j.j(SourceFile:45)
	at aa.b.c(Unknown Source:24)
	at aa.g$a.d(Unknown Source:31)
	at aa.g.b(Unknown Source:38)
	at e9.h.a(SourceFile:12)
	at b9.d.c(Unknown Source:60)
	... 8 more
Caused by: java.lang.NoSuchMethodException: ba.r.<init> [class ba.w]
	at java.lang.Class.getConstructor0(Class.java:2363)
	at java.lang.Class.getConstructor(Class.java:1759)
	at b9.j.j(SourceFile:33)
	... 13 more
}
```

**Comment by chr56** [comment]
Upgrade to [v0.5.4.1](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.5.4.1) first.

Thank you!

**Comment by chr56** [comment]
The `versionCode` is unchanged. So install it again!

**Comment by anaskaejdar** [comment]
Done. The error doesn't appear anymore: very good and very weird, thank you.
