### ISSUE TITLE
[Bug]: Failed to save tag in new Tag Editor

### ISSUE THREAD

**Issue by chr56** [chr56/Phonograph_Plus#63]
### Bug Summary

In **some devices**, though the permission of full file access is already granted, Phonograph Plus still reports an Internal Error:

```
Failed to write tag!
z8.b: z8.g: Cannot modify 01 Collapsed in <SONG_FILE> because do not have permissions to create files in the folder <FOLDER_NAME>
```

### Version

since `0.6.0`

**Comment by Tarkin22** [comment]
I tried with adding artist name in folder. Crash log in my case:

```Package name:    player.phonograph.plus
App version:     0.6.3 (530)
Git Commit Hash: 85536e54bf1b7f9519a8
Android version: 10 (SDK 29)
Device brand:    Xiaomi  (by Xiaomi)
Device model:    POCOPHONE F1 (code: beryllium)
Product name:    beryllium
Build version:   QKQ1.190828.002 release-keys 
                 (V12.0.3.0.QEJMIXM)
Hardware:        qcom
Language:        pl

java.lang.IllegalArgumentException: can not write /storage/34AE-C19C/Music/Partiboi69 - UNPREC069/Partiboi69 - UNPREC069 - 01 Booty Flow.wav
	at ra.b.applyEditImpl(SourceFile:212)
	at ra.c.invokeSuspend(Unknown Source:32)
	at e6.a.resumeWith(Unknown Source:8)
	at u6.l0.run(Unknown Source:104)
	at kotlinx.coroutines.internal.g.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.k.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a.run(SourceFile:65)
	Suppressed: u6.j0: [x1{Cancelling}@e0ac06d, Dispatchers.Default]```
