### ISSUE TITLE
 [Bug Report] Crash when modifying Library Categories 

### ISSUE THREAD

**Issue by elesto** [chr56/Phonograph_Plus#7]
**Describe the bug or unexpected behavi
crash when moving and changing library categories in the settings

**Crash log**
```Crash Report:

Package name:    player.phonograph.plus
App version:     0.2.2 (204)
Git Commit Hash: 8ece1e4f4973468432e7
Android version: 12 (SDK 31)
Device brand:    Sony  (by Sony)
Device model:    XQ-AS72 (code: XQ-AS72)
Product name:    XQ-AS72
Build version:   58.2.A.2.90 
                 (058002A002009003718185433)
Hardware:        qcom
Language:        en

java.lang.NullPointerException
	at z7.f$b.move(Unknown Source:4)
	at z7.f.onViewMoved(Unknown Source:2)
	at u9.c.i(:2)
	at androidx.recyclerview.widget.k.q(:4)
	at androidx.recyclerview.widget.k$b.b(Unknown Source:112)
	at androidx.recyclerview.widget.RecyclerView.onTouchEvent(:1)
	at android.view.View.dispatchTouchEvent(View.java:14551)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3114)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2787)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:519)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1896)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:864)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:477)
	at android.view.View.dispatchPointerEvent(View.java:14810)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6351)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6152)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5630)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5687)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5653)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5818)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5661)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5875)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5634)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5687)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5653)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5661)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5634)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8574)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8525)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8493)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8697)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:260)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:240)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8654)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8783)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1120)
	at android.view.Choreographer.doCallbacks(Choreographer.java:926)
	at android.view.Choreographer.doFrame(Choreographer.java:851)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1105)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:346)
	at android.os.Looper.loop(Looper.java:475)
	at android.app.ActivityThread.main(ActivityThread.java:7889)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)```

and:

```Crash Report:

Package name:    player.phonograph.plus
App version:     0.2.2 (204)
Git Commit Hash: 8ece1e4f4973468432e7
Android version: 12 (SDK 31)
Device brand:    Sony  (by Sony)
Device model:    XQ-AS72 (code: XQ-AS72)
Product name:    XQ-AS72
Build version:   58.2.A.2.90 
                 (058002A002009003718185433)
Hardware:        qcom
Language:        en

java.lang.IllegalStateException: position0 is invalid!
	at z7.f.p(:3)
	at z7.d.onClick(Unknown Source:16)
	at android.view.View.performClick(View.java:7451)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.access$3700(View.java:842)
	at android.view.View$PerformClick.run(View.java:28690)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:346)
	at android.os.Looper.loop(Looper.java:475)
	at android.app.ActivityThread.main(ActivityThread.java:7889)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)```

**Comment by chr56** [comment]
I see. And honestly I sometimes I meet this as well.
