### ISSUE TITLE
Errors reading ogg files from newpipe

### ISSUE THREAD

**Issue by pouek** [chr56/Phonograph_Plus#74]
Hi, I receive these error messages when phonograh tries to read some files downloaded with newpipe. It is opus in ogg containers if I get it right.

"Failed to read song file
v8.a: OggS Header could not be found, not an ogg stream Eߣ
	at e9.a.a(SourceFile:80)
	at y8.d.c(Unknown Source:60)
	at n8.b.a(SourceFile:97)
	at ta.h.a(Unknown Source:3)
	at ta.h$c.invokeSuspend(Unknown Source:12)
	at h6.a.resumeWith(Unknown Source:8)
	at y6.q0.run(Unknown Source:102)
	at kotlinx.coroutines.internal.i.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a$a.run(SourceFile:63)
}"

Config details :
"Package name:    player.phonograph.plus
App version:     0.6.1 (510)
Git Commit Hash: fc429ef6a8acd7087ddb
Android version: 13 (SDK 33)
Device brand:    OnePlus  (by OnePlus)
Device model:    ONEPLUS A5000 (code: OnePlus5)
Product name:    OnePlus5
Build version:   TQ2A.230305.008.C1 
                 (eng.emy.20230321.225445)
Hardware:        qcom
Language:        fr"

**Comment by pixel2user** [comment]
I can play opus files created by NewPipe without problems.

Package name:    player.phonograph.plus
App version:     1.3.2 (1032)
Git Commit Hash: e5fd7bf0db27965a967f680490fbedd07dc23f60
Android version: 12 (SDK 32)
Device brand:    google  (by Google)

**Comment by chr56** [comment]
This error notification has been muted since v1.4.0. No more such spamming error notifications no matter whether your files are corrupted or not.

Close anyway.
