### ISSUE TITLE
[Bug Report] Crash when long pressing on any album

### ISSUE THREAD

**Issue by WaifuPX-DG** [chr56/Phonograph_Plus#8]
Crash Report:

Package name:    player.phonograph.plus
App version:     0.2.2 (204)
Git Commit Hash: 8ece1e4f4973468432e7
Android version: 11 (SDK 30)
Device brand:    Redmi  (by Xiaomi)
Device model:    M2004J19C (code: lancelot)
Product name:    lancelot_global
Build version:   RP1A.200720.011 
                 (V12.5.5.0.RJCMIXM)
Hardware:        mt6768
Language:        es

java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
 ViewHolder 1:a{aae0138 position=3 id=459805675864067378, oldPos=-1, pLpos:-1 not recyclable(1)} 
 View Holder 2:a{c375125 position=1 id=459805675864067378, oldPos=-1, pLpos:-1} com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView{9c5c511 VFED..... ......ID 0,0-1080,1826 #7f090274 app:id/recycler_view}, adapter:c8.a@7664676, layout:androidx.recyclerview.widget.GridLayoutManager@5482477, context:player.phonograph.ui.activities.MainActivity@fc47741
	at androidx.recyclerview.widget.RecyclerView.y(:11)
	at androidx.recyclerview.widget.RecyclerView.onLayout(:2)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.r(:14)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(:2)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at androidx.recyclerview.widget.RecyclerView$m.l0(Unknown Source:32)
	at androidx.recyclerview.widget.LinearLayoutManager.y1(Unknown Source:166)
	at androidx.recyclerview.widget.LinearLayoutManager.i1(:2)
	at androidx.recyclerview.widget.LinearLayoutManager.B0(:17)
	at androidx.recyclerview.widget.RecyclerView.A(Unknown Source:66)
	at androidx.recyclerview.widget.RecyclerView.y(Unknown Source:71)
	at androidx.recyclerview.widget.RecyclerView.onLayout(:2)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at androidx.viewpager2.widget.ViewPager2.onLayout(Unknown Source:70)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at com.google.android.material.appbar.g.t(:2)
	at com.google.android.material.appbar.h.h(Unknown Source:0)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(:2)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at com.sothree.slidinguppanel.SlidingUpPanelLayout.onLayout(Unknown Source:140)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(Unknown Source:56)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:804)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3702)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3160)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2129)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8603)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:975)
	at android.view.Choreographer.doCallbacks(Choreographer.java:799)
	at android.view.Choreographer.doFrame(Choreographer.java:734)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:960)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7864)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

**How to reproduce**
• long press on any album

**Comment by chr56** [comment]
Can you show me the 2nd and 4th albums in you album list causing crashes?

**Comment by WaifuPX-DG** [comment]
![IMG_20220420_100142](https://user-images.githubusercontent.com/78942037/164261244-ac340085-7b70-4207-80f6-784586501237.jpg)


Now that I notice it, only pressing 2 & 4 causes closing, in the others there is no problem

**Comment by WaifuPX-DG** [comment]
If I change the grid size to 3, the ones that cause closure are album 1, 2 and 4

**Comment by chr56** [comment]
I am aware of this issue, it would be fixed in next version.

**Comment by chr56** [comment]
This should be fixed in [v0.2.3-RC2](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.2.3-RC2)
