### ISSUE TITLE
[Crash Report]: App crashes when trying to save changes in Tag Editor if "Allow access to all files" permission is denied

### ISSUE THREAD

**Issue by Quintus19** [chr56/Phonograph_Plus#81]
### Crash log

As the title says.

```
Crash Report:

Package name:    player.phonograph.plus
App version:     0.6.2.1 (521)
Git Commit Hash: 90e69dd46fcd73aafcc1
Android version: 11 (SDK 30)
Device brand:    samsung  (by samsung)
Device model:    SM-A105F (code: a10)
Product name:    a10dd
Build version:   RP1A.200720.012.A105FDDS9CWB3 
                 (A105FDDS9CWB3)
Hardware:        exynos7884B
Language:        en

java.lang.IllegalArgumentException: can not write /storage/3D0B-92FC/Music/Video Game Soundtracks/Cave Story/Famitracks/RushJet1 - Cave Story - Famitracks - 31 Last Battle.flac
	at wa.b.applyEditImpl(SourceFile:212)
	at wa.e$a.invokeSuspend(Unknown Source:15)
	at h6.a.resumeWith(Unknown Source:8)
	at y6.p0.run(Unknown Source:102)
	at kotlinx.coroutines.internal.i.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a$a.run(SourceFile:63)
	Suppressed: y6.n0: [y1{Cancelling}@aafe99a, Dispatchers.Default]
```

### Steps to reproduce the bug

0: ```Allow access to all files``` permission *must* be denied to reproduce this bug.

1: Open Tag Editor and make some changes

2: Tap the save icon and approve changes

3: *app crashes*

### Version

0.6.2.1

**Comment by chr56** [comment]
Changed in revision 47d1a5be8c06e6709670790b048f4f64dfa6d32b:

Navigate to storage setting or app detail if no full storage permission instead of saving and then crashing.

**Comment by chr56** [comment]
[v0.6.3](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.6.3) released! 
Close!
