### ISSUE TITLE
[Crash Report]: Artist in search results crashes the app

### ISSUE THREAD

**Issue by Nathoufresh** [chr56/Phonograph_Plus#91]
### Crash log

```
Crash Report:

Package name:    player.phonograph.plus
App version:     0.7.0 (600)
Git Commit Hash: 190d18826661b2e655f8
Android version: 13 (SDK 33)
Device brand:    google  (by Google)
Device model:    Pixel 6a (code: bluejay)
Product name:    bluejay
Build version:   TQ3A.230605.010 
                 (10121037)
Hardware:        bluejay
Language:        en

java.lang.ClassCastException: player.phonograph.model.Artist cannot be cast to player.phonograph.model.Album
	at ha.i.c(SourceFile:54)
	at ha.l.j(SourceFile:23)
	at ha.e.onClick(SourceFile:15)
	at android.view.View.performClick(View.java:7542)
	at android.view.View.performClickInternal(View.java:7519)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29476)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Steps to reproduce the bug

Can be reproduced by searching for a string then clicking on a matching artist. 

### Version

0.7.0 (F-Droid)

**Comment by ayuinaba** [comment]
Having the exact same issue.
Furthermore, the app takes a long time to even open (maybe 10 seconds), which wasn't happening before.

```
Crash Report:

Package name:    [player.phonograph.plus](http://player.phonograph.plus/)
App version:     0.7.0 (600)
Git Commit Hash: 190d18826661b2e655f8
Android version: 13 (SDK 33)
Device brand:    asus  (by asus)
Device model:    Zenfone Max Pro M1 (code: X00TD)
Product name:    lineage_X00TD
Build version:   lineage_X00TD-userdebug 13 TQ2A.230305.008.C1 eng.root.20230415.040047 dev-keys 
                 (eng.root.20230415.040047)
Hardware:        qcom
Language:        en

java.lang.ClassCastException: player.phonograph.model.Artist cannot be cast to player.phonograph.model.Album
	at ha.i.c(SourceFile:54)
	at ha.l.j(SourceFile:23)
	at ha.e.onClick(SourceFile:15)
	at android.view.View.performClick([View.java:7506](http://view.java:7506/))
	at android.view.View.performClickInternal([View.java:7483](http://view.java:7483/))
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$[PerformClick.run](http://performclick.run/)([View.java:29357](http://view.java:29357/))
	at android.os.Handler.handleCallback([Handler.java:942](http://handler.java:942/))
	at android.os.Handler.dispatchMessage([Handler.java:99](http://handler.java:99/))
	at android.os.Looper.loopOnce([Looper.java:201](http://looper.java:201/))
	at android.os.Looper.loop([Looper.java:288](http://looper.java:288/))
	at [android.app](http://android.app/).ActivityThread.main([ActivityThread.java:7884](http://activitythread.java:7884/))
	at java.lang.reflect.Method.invoke(Native Method)
	at [com.android](http://com.android/).internal.os.RuntimeInit$[MethodAndArgsCaller.run](http://methodandargscaller.run/)([RuntimeInit.java:548](http://runtimeinit.java:548/))
	at [com.android](http://com.android/).internal.os.ZygoteInit.main([ZygoteInit.java:936](http://zygoteinit.java:936/))
```

**Comment by chr56** [comment]
Confirmed.

**Comment by chr56** [comment]
May I ask how many songs are in your device, @ayuinabav?

**Comment by chr56** [comment]
And in your "10 seconds", does the app take longer to open in _Splash Screen_ (white/black screen with the app icon in center) or in the state of _"user interface has already showed but items (songs etc.) have not"_.

**Comment by chr56** [comment]
Fixed in 2bef5775fee7840e22fc23bbe09499b36b29925d, 
and startup performance should be improved after 50b0f60daeb3aaf9c1248b5247ae67298e2d5a48.

**Comment by ayuinaba** [comment]
> May I ask how many songs are in your device, @ayuinaba ?

12704 songs, currently.

> And in your "10 seconds", does the app take longer to open in _Splash Screen_ (white/black screen with the app icon in center) or in the state of _"user interface has already showed but items (songs etc.) have not"_. @ayuinaba

Splash screen. Sometimes, the logo fails to appear as well and it seems to hang there, but it eventually opens.

**Comment by chr56** [comment]
Preview [v0.7.1-dev1](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_0.7.1-dev1) has released:
Crash has been fixed.
Start-up Performance should be improved.

**Comment by ayuinaba** [comment]
> Preview [v0.7.1-dev1](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_0.7.1-dev1) has released: Crash has been fixed. Start-up Performance should be improved.

Crash was fixed, indeed. Thank you very much for your efforts.
The start-up time still takes about the same, however. Not sure if I should open a new issue or not. It would be much faster before the last stable version (iirc).

**Comment by chr56** [comment]
[v0.7.1](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.7.1) has released.

Close!

**Comment by chr56** [comment]
@ayuinaba, the performance discussion would be moved to **Issue #94**.
